use crate::ast::*;

/// Generates Rust code from a verified Soma AST.
/// Phase 1: generates struct skeletons and trait definitions.
pub struct CodeGen {
    output: String,
    indent: usize,
}

impl CodeGen {
    pub fn new() -> Self {
        Self {
            output: String::new(),
            indent: 0,
        }
    }

    pub fn generate(&mut self, program: &Program) -> String {
        self.emit_line("// Generated by Soma compiler v0.1.0");
        self.emit_line("// Do not edit — regenerate from .cell source");
        self.emit_line("");
        self.emit_line("use std::collections::HashMap;");
        self.emit_line("use std::sync::{Arc, RwLock};");
        self.emit_line("");

        for cell in &program.cells {
            // Skip meta-cells — they define the language, not the program
            if cell.node.kind != CellKind::Cell {
                continue;
            }
            self.generate_cell(&cell.node, true);
        }

        self.output.clone()
    }

    fn generate_cell(&mut self, cell: &CellDef, is_top_level: bool) {
        let mod_name = to_snake_case(&cell.name);

        if is_top_level {
            self.emit_line(&format!("pub mod {} {{", mod_name));
            self.indent += 1;
            self.emit_line("use super::*;");
            self.emit_line("");
        }

        // Generate state struct from memory section
        self.generate_state_struct(cell);

        // Generate trait from face section
        self.generate_face_trait(cell);

        // Generate signal enums
        self.generate_signal_types(cell);

        // Generate children modules
        for section in &cell.sections {
            if let Section::Interior(ref interior) = section.node {
                for child in &interior.cells {
                    self.emit_line("");
                    self.generate_cell(&child.node, true);
                }
            }
        }

        if is_top_level {
            self.indent -= 1;
            self.emit_line("}");
            self.emit_line("");
        }
    }

    fn generate_state_struct(&mut self, cell: &CellDef) {
        let mut has_memory = false;

        for section in &cell.sections {
            if let Section::Memory(ref mem) = section.node {
                has_memory = true;
                self.emit_line(&format!("pub struct {}State {{", cell.name));
                self.indent += 1;

                for slot in &mem.slots {
                    let rust_type = self.type_to_rust(&slot.node.ty.node);
                    let wrapped = self.wrap_for_properties(&rust_type, &slot.node.properties);
                    self.emit_line(&format!("pub {}: {},", slot.node.name, wrapped));
                }

                self.indent -= 1;
                self.emit_line("}");
                self.emit_line("");
            }
        }

        if !has_memory {
            self.emit_line(&format!("pub struct {}State;", cell.name));
            self.emit_line("");
        }
    }

    fn generate_face_trait(&mut self, cell: &CellDef) {
        for section in &cell.sections {
            if let Section::Face(ref face) = section.node {
                self.emit_line(&format!("pub trait {}Face {{", cell.name));
                self.indent += 1;

                for decl in &face.declarations {
                    match &decl.node {
                        FaceDecl::Signal(sig) => {
                            let params = self.params_to_rust(&sig.params);
                            let ret = match &sig.return_type {
                                Some(t) => format!(" -> {}", self.type_to_rust(&t.node)),
                                None => String::new(),
                            };
                            self.emit_line(&format!(
                                "fn {}(&self{}){};",
                                to_snake_case(&sig.name),
                                if params.is_empty() {
                                    String::new()
                                } else {
                                    format!(", {}", params)
                                },
                                ret,
                            ));
                        }
                        FaceDecl::Given(given) => {
                            // Given declarations become constructor parameters
                            self.emit_line(&format!(
                                "// given: {}: {}",
                                given.name,
                                self.type_to_rust(&given.ty.node)
                            ));
                        }
                        FaceDecl::Promise(promise) => {
                            self.emit_line(&format!(
                                "// promise: {}",
                                self.constraint_to_comment(&promise.constraint.node)
                            ));
                        }
                        FaceDecl::Await(aw) => {
                            let params = self.params_to_rust(&aw.params);
                            self.emit_line(&format!(
                                "// await: {}({})",
                                aw.name, params
                            ));
                        }
                    }
                }

                self.indent -= 1;
                self.emit_line("}");
                self.emit_line("");
            }
        }
    }

    fn generate_signal_types(&mut self, cell: &CellDef) {
        let mut signals: Vec<&SignalDecl> = Vec::new();

        for section in &cell.sections {
            if let Section::Face(ref face) = section.node {
                for decl in &face.declarations {
                    if let FaceDecl::Signal(ref sig) = decl.node {
                        signals.push(sig);
                    }
                }
            }
        }

        if !signals.is_empty() {
            self.emit_line(&format!("#[derive(Debug, Clone)]"));
            self.emit_line(&format!("pub enum {}Signal {{", cell.name));
            self.indent += 1;

            for sig in &signals {
                if sig.params.is_empty() {
                    self.emit_line(&format!("{},", to_pascal_case(&sig.name)));
                } else {
                    let fields: Vec<String> = sig
                        .params
                        .iter()
                        .map(|p| self.type_to_rust(&p.ty.node))
                        .collect();
                    self.emit_line(&format!(
                        "{}({}),",
                        to_pascal_case(&sig.name),
                        fields.join(", ")
                    ));
                }
            }

            self.indent -= 1;
            self.emit_line("}");
            self.emit_line("");
        }
    }

    // ── Type mapping ─────────────────────────────────────────────────

    fn type_to_rust(&self, ty: &TypeExpr) -> String {
        match ty {
            TypeExpr::Simple(name) => match name.as_str() {
                "Int" => "i64".to_string(),
                "Float" => "f64".to_string(),
                "String" => "String".to_string(),
                "Bool" => "bool".to_string(),
                other => other.to_string(),
            },
            TypeExpr::Generic { name, args } => {
                let arg_strs: Vec<String> = args.iter().map(|a| self.type_to_rust(&a.node)).collect();
                match name.as_str() {
                    "Map" => format!("HashMap<{}>", arg_strs.join(", ")),
                    "List" => format!("Vec<{}>", arg_strs.join(", ")),
                    "Set" => format!("std::collections::HashSet<{}>", arg_strs.join(", ")),
                    "Log" => format!("Vec<{}>", arg_strs.join(", ")), // Log as append-only Vec
                    "Option" => format!("Option<{}>", arg_strs.join(", ")),
                    "Result" => format!("Result<{}>", arg_strs.join(", ")),
                    other => format!("{}<{}>", other, arg_strs.join(", ")),
                }
            }
            TypeExpr::CellRef { cell, member } => {
                format!("{}::{}", to_snake_case(cell), member)
            }
        }
    }

    fn wrap_for_properties(&self, rust_type: &str, properties: &[Spanned<MemoryProperty>]) -> String {
        let flag_names: Vec<&str> = properties
            .iter()
            .filter_map(|p| match &p.node {
                MemoryProperty::Flag(name) => Some(name.as_str()),
                _ => None,
            })
            .collect();

        // Wrap in Arc<RwLock<>> for concurrent access on consistent state
        if flag_names.contains(&"consistent") {
            format!("Arc<RwLock<{}>>", rust_type)
        } else {
            rust_type.to_string()
        }
    }

    fn params_to_rust(&self, params: &[Param]) -> String {
        params
            .iter()
            .map(|p| format!("{}: {}", to_snake_case(&p.name), self.type_to_rust(&p.ty.node)))
            .collect::<Vec<_>>()
            .join(", ")
    }

    fn constraint_to_comment(&self, constraint: &Constraint) -> String {
        match constraint {
            Constraint::Descriptive(s) => s.clone(),
            Constraint::Comparison { left, op, right } => {
                format!("{:?} {} {:?}", left.node, op, right.node)
            }
            Constraint::Predicate { name, args: _ } => {
                format!("{}(..)", name)
            }
            Constraint::And(a, b) => {
                format!(
                    "{} && {}",
                    self.constraint_to_comment(&a.node),
                    self.constraint_to_comment(&b.node)
                )
            }
            Constraint::Or(a, b) => {
                format!(
                    "{} || {}",
                    self.constraint_to_comment(&a.node),
                    self.constraint_to_comment(&b.node)
                )
            }
            Constraint::Not(inner) => {
                format!("!{}", self.constraint_to_comment(&inner.node))
            }
        }
    }

    // ── Output helpers ─────��─────────────────────────────────────────

    fn emit_line(&mut self, line: &str) {
        if line.is_empty() {
            self.output.push('\n');
        } else {
            for _ in 0..self.indent {
                self.output.push_str("    ");
            }
            self.output.push_str(line);
            self.output.push('\n');
        }
    }
}

fn to_snake_case(s: &str) -> String {
    let mut result = String::new();
    for (i, ch) in s.chars().enumerate() {
        if ch.is_ascii_uppercase() {
            if i > 0 {
                result.push('_');
            }
            result.push(ch.to_ascii_lowercase());
        } else {
            result.push(ch);
        }
    }
    result
}

fn to_pascal_case(s: &str) -> String {
    let mut result = String::new();
    let mut capitalize_next = true;
    for ch in s.chars() {
        if ch == '_' {
            capitalize_next = true;
        } else if capitalize_next {
            result.push(ch.to_ascii_uppercase());
            capitalize_next = false;
        } else {
            result.push(ch);
        }
    }
    result
}
