//! Generates Rust source from [native] handler AST.
//!
//! The output is a single .rs file with `#[no_mangle] pub extern "C"` functions
//! that can be compiled into a cdylib and loaded via FFI.

use crate::ast::*;
use std::collections::{HashMap, HashSet};

/// Type inferred for a local variable
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum NativeType {
    Int,
    Float,
    Bool,
}

impl NativeType {
    fn rust_str(&self) -> &'static str {
        match self {
            NativeType::Int => "i64",
            NativeType::Float => "f64",
            NativeType::Bool => "bool",
        }
    }
    /// Type for computation inside [native] handlers — BigInt for ints
    fn compute_str(&self) -> &'static str {
        match self {
            NativeType::Int => "BigInt",
            NativeType::Float => "f64",
            NativeType::Bool => "bool",
        }
    }
}

/// Information about a native handler to be compiled
pub struct NativeHandler {
    pub cell_name: String,
    pub signal_name: String,
    pub params: Vec<Param>,
    pub body: Vec<Spanned<Statement>>,
}

/// FFI signature info: param types + return type
#[derive(Debug, Clone)]
pub struct NativeSig {
    pub fn_name: String,
    pub param_types: Vec<NativeType>,
    pub return_type: NativeType,
    /// If true, args are passed via shared buffer (_soma_push_*), not C params
    pub uses_shared_args: bool,
}

/// Parallel configuration for code generation
#[derive(Debug, Clone, Default)]
pub struct ParallelConfig {
    pub enabled: bool,
    pub handlers: Vec<String>,
    pub threads: usize,
}

/// Generate Rust source for a set of native handlers in one cell.
pub fn generate_native_source(handlers: &[NativeHandler]) -> (String, Vec<NativeSig>) {
    generate_native_source_with_config(handlers, &ParallelConfig::default())
}

pub fn generate_native_source_with_config(handlers: &[NativeHandler], parallel: &ParallelConfig) -> (String, Vec<NativeSig>) {
    let mut out = String::new();
    let mut sigs = Vec::new();

    out.push_str("// Generated by Soma compiler — [native] handlers\n");
    out.push_str("// Do not edit — regenerate from .cell source\n");
    out.push_str("use num_bigint::BigInt;\n");
    out.push_str("use num_traits::ToPrimitive;\n\n");

    // Check if any handler uses random()
    let uses_random = handlers.iter().any(|h| body_uses_random(&h.body));
    if uses_random {
        out.push_str("static mut _SOMA_RNG_STATE: u64 = 0x12345678_9abcdef0;\n\n");
        out.push_str("#[inline(always)]\nunsafe fn _soma_random() -> f64 {\n");
        out.push_str("    _SOMA_RNG_STATE ^= _SOMA_RNG_STATE >> 12;\n");
        out.push_str("    _SOMA_RNG_STATE ^= _SOMA_RNG_STATE << 25;\n");
        out.push_str("    _SOMA_RNG_STATE ^= _SOMA_RNG_STATE >> 27;\n");
        out.push_str("    let r = _SOMA_RNG_STATE.wrapping_mul(0x2545F4914F6CDD1D);\n");
        out.push_str("    (r >> 11) as f64 / ((1u64 << 53) as f64)\n");
        out.push_str("}\n\n");
    }

    // Build set of sibling native handler names for inter-call resolution
    let siblings: HashSet<String> = handlers.iter().map(|h| h.signal_name.clone()).collect();

    // Check if any handler returns Int (needs the V enum for BigInt auto-promotion).
    // Emit V once at the top rather than per-handler.
    let any_int_return = handlers.iter().any(|h| {
        let mut gen = FnGenerator::new(&h.params, &siblings, &format!("handler_{}", h.signal_name));
        for p in &h.params {
            let ty = type_expr_to_native(&p.ty.node);
            gen.var_types.insert(p.name.clone(), ty);
        }
        gen.infer_body_types(&h.body);
        gen.infer_return_type(&h.body) == NativeType::Int
    });
    let mut v_enum_emitted = false;

    for handler in handlers {
        let mut gen = FnGenerator::new(&handler.params, &siblings, &format!("handler_{}", handler.signal_name));

        // Infer types from params
        for p in &handler.params {
            let ty = type_expr_to_native(&p.ty.node);
            gen.var_types.insert(p.name.clone(), ty);
        }

        // Pre-scan body to infer local variable types
        gen.infer_body_types(&handler.body);

        let fn_name = format!("handler_{}", handler.signal_name);

        // Build param list
        let param_str: String = handler.params.iter()
            .map(|p| {
                let ty = type_expr_to_native(&p.ty.node);
                format!("{}: {}", p.name, ty.rust_str())
            })
            .collect::<Vec<_>>()
            .join(", ");

        // Determine return type from body (look for return statements)
        let ret_type = gen.infer_return_type(&handler.body);

        if ret_type == NativeType::Int {
            // Inline overflow caching: use i64 until overflow, then promote
            // to BigInt and continue from the exact overflow point. No restart.

            // Helper: checked i64 ops that promote to BigInt on overflow — emit once
            if !v_enum_emitted {
                v_enum_emitted = true;
            out.push_str("
/// A value that starts as i64 and promotes to BigInt on overflow
enum V { S(i64), B(BigInt) }
impl V {
    fn add(&mut self, other: i64) {
        *self = match self {
            V::S(a) => match a.checked_add(other) {
                Some(r) => V::S(r),
                None => V::B(BigInt::from(*a) + other),
            },
            V::B(a) => { *a += other; return; }
        };
    }
    fn sub(&mut self, other: i64) {
        *self = match self {
            V::S(a) => match a.checked_sub(other) {
                Some(r) => V::S(r),
                None => V::B(BigInt::from(*a) - other),
            },
            V::B(a) => { *a -= other; return; }
        };
    }
    fn mul_v(&mut self, other: &V) {
        *self = match (&*self, other) {
            (V::S(a), V::S(b)) => match a.checked_mul(*b) {
                Some(r) => V::S(r),
                None => V::B(BigInt::from(*a) * *b),
            },
            (V::S(a), V::B(b)) => V::B(BigInt::from(*a) * b),
            (V::B(a), V::S(b)) => V::B(a.clone() * *b),
            (V::B(a), V::B(b)) => V::B(a.clone() * b),
        };
    }
    fn add_v(&mut self, other: &V) {
        *self = match (&*self, other) {
            (V::S(a), V::S(b)) => match a.checked_add(*b) {
                Some(r) => V::S(r),
                None => V::B(BigInt::from(*a) + *b),
            },
            (V::S(a), V::B(b)) => V::B(BigInt::from(*a) + b),
            (V::B(a), V::S(b)) => V::B(a.clone() + *b),
            (V::B(a), V::B(b)) => V::B(a.clone() + b),
        };
    }
    fn sub_v(&mut self, other: &V) {
        *self = match (&*self, other) {
            (V::S(a), V::S(b)) => match a.checked_sub(*b) {
                Some(r) => V::S(r),
                None => V::B(BigInt::from(*a) - *b),
            },
            (V::S(a), V::B(b)) => V::B(BigInt::from(*a) - b),
            (V::B(a), V::S(b)) => V::B(a.clone() - *b),
            (V::B(a), V::B(b)) => V::B(a.clone() - b),
        };
    }
    fn div_v(&mut self, other: &V) {
        *self = match (&*self, other) {
            (V::S(a), V::S(b)) => V::S(*a / *b),
            (V::S(a), V::B(b)) => V::B(BigInt::from(*a) / b),
            (V::B(a), V::S(b)) => V::B(a.clone() / *b),
            (V::B(a), V::B(b)) => V::B(a.clone() / b),
        };
    }
    fn mod_v(&mut self, other: &V) {
        *self = match (&*self, other) {
            (V::S(a), V::S(b)) => V::S(*a % *b),
            (V::S(a), V::B(b)) => V::B(BigInt::from(*a) % b),
            (V::B(a), V::S(b)) => V::B(a.clone() % *b),
            (V::B(a), V::B(b)) => V::B(a.clone() % b),
        };
    }
    fn to_i64(&self) -> Option<i64> {
        match self { V::S(n) => Some(*n), V::B(n) => n.to_i64() }
    }
    fn to_bigint(&self) -> BigInt {
        match self { V::S(n) => BigInt::from(*n), V::B(n) => n.clone() }
    }
    fn le_v(&self, other: &V) -> bool {
        match (self, other) {
            (V::S(a), V::S(b)) => *a <= *b,
            (V::S(a), V::B(b)) => BigInt::from(*a) <= *b,
            (V::B(a), V::S(b)) => *a <= BigInt::from(*b),
            (V::B(a), V::B(b)) => *a <= *b,
        }
    }
    fn lt_v(&self, other: &V) -> bool {
        match (self, other) {
            (V::S(a), V::S(b)) => *a < *b,
            (V::S(a), V::B(b)) => BigInt::from(*a) < *b,
            (V::B(a), V::S(b)) => *a < BigInt::from(*b),
            (V::B(a), V::B(b)) => *a < *b,
        }
    }
    fn clone_v(&self) -> V {
        match self { V::S(n) => V::S(*n), V::B(n) => V::B(n.clone()) }
    }
}
impl std::fmt::Display for V {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self { V::S(n) => write!(f, \"{}\"  , n), V::B(n) => write!(f, \"{}\"  , n) }
    }
}

// Shared arg buffer for BigInt-capable calls
static mut _SOMA_ARGS: Vec<V> = Vec::new();
static mut _SOMA_RESULT: Option<String> = None;

#[no_mangle]
pub extern \"C\" fn _soma_clear_args() {
    unsafe { _SOMA_ARGS.clear(); }
}

#[no_mangle]
pub extern \"C\" fn _soma_push_i64(v: i64) {
    unsafe { _SOMA_ARGS.push(V::S(v)); }
}

#[no_mangle]
pub extern \"C\" fn _soma_push_bigint(ptr: *const u8, len: i64) {
    unsafe {
        let bytes = std::slice::from_raw_parts(ptr, len as usize);
        let s = std::str::from_utf8_unchecked(bytes);
        let negative = s.starts_with('-');
        let digits = if negative { &s[1..] } else { s };
        let big: BigInt = digits.parse().unwrap();
        _SOMA_ARGS.push(V::B(if negative { -big } else { big }));
    }
}

#[no_mangle]
pub extern \"C\" fn _soma_result_ptr() -> *const u8 {
    unsafe { _SOMA_RESULT.as_ref().map(|s| s.as_ptr()).unwrap_or(std::ptr::null()) }
}

#[no_mangle]
pub extern \"C\" fn _soma_result_len() -> i64 {
    unsafe { _SOMA_RESULT.as_ref().map(|s| s.len() as i64).unwrap_or(0) }
}
");
            } // end v_enum_emitted guard

            // Generate zero-arg function that reads from shared buffer
            out.push_str(&format!("#[no_mangle]\npub extern \"C\" fn {}() -> i64 {{\n", fn_name));

            // Read params from shared buffer
            for (i, p) in handler.params.iter().enumerate() {
                let ty = type_expr_to_native(&p.ty.node);
                if ty == NativeType::Int {
                    out.push_str(&format!("    let {} = unsafe {{ _SOMA_ARGS[{}].clone_v() }};\n", p.name, i));
                } else {
                    // Float/Bool params: read as i64 bits then interpret
                    out.push_str(&format!("    let {} = unsafe {{ match &_SOMA_ARGS[{}] {{ V::S(n) => *n as {}, _ => 0 as {} }} }};\n",
                        p.name, i, ty.rust_str(), ty.rust_str()));
                }
            }

            // Generate body with V type
            for stmt in &handler.body {
                let code = gen.gen_stmt(&stmt.node, 1);
                // Transform BigInt code → V code
                let code = code
                    .replace(": BigInt", ": V")
                    .replace("BigInt::from(", "V::S(");

                // Transform assignment arithmetic patterns:
                // x = ((&x) OP (&y));  →  x.OP_v(&y); (in-place)
                // x = ((&x) OP V::S(N));  →  x.OP(N); (in-place with literal)
                let code = transform_v_arithmetic(&code);
                out.push_str(&code);
            }
            {
                let last_is_return = handler.body.last()
                    .map(|s| matches!(s.node, Statement::Return { .. }))
                    .unwrap_or(false);
                if !last_is_return { out.push_str("    0i64\n"); }
            }
            out.push_str("}\n\n");

            // BigInt result is read via shared _soma_result_ptr/_soma_result_len
        } else {
            out.push_str(&format!("#[no_mangle]\npub extern \"C\" fn {}({}) -> {} {{\n",
                fn_name, param_str, ret_type.rust_str()));
            for stmt in &handler.body {
                out.push_str(&gen.gen_stmt(&stmt.node, 1));
            }
            let last_is_return = handler.body.last()
                .map(|s| matches!(s.node, Statement::Return { .. }))
                .unwrap_or(false);
            if !last_is_return {
                let default = match ret_type {
                    NativeType::Float => "    0.0f64\n",
                    NativeType::Bool => "    false\n",
                    _ => "    0i64\n",
                };
                out.push_str(default);
            }
            out.push_str("}\n\n");
        }

        // Generate parallel version if handler is in the parallel list
        let is_parallel = parallel.enabled && parallel.handlers.contains(&handler.signal_name);
        if is_parallel && !handler.params.is_empty() {
            let n_threads = if parallel.threads > 0 { parallel.threads } else { 0 };
            let threads_expr = if n_threads > 0 {
                format!("{}usize", n_threads)
            } else {
                "std::thread::available_parallelism().map(|n| n.get()).unwrap_or(1)".to_string()
            };

            // Parallel strategy: split the FIRST param (iteration count) across threads.
            // Each thread calls the sequential handler with chunk_size.
            // Results are averaged (weighted by chunk size).
            // This works for any Monte Carlo / accumulation handler.
            let first_param = &handler.params[0].name;
            let other_params: Vec<String> = handler.params[1..].iter()
                .map(|p| format!("{}: {}", p.name, type_expr_to_native(&p.ty.node).rust_str()))
                .collect();
            let other_args: Vec<String> = handler.params[1..].iter()
                .map(|p| p.name.clone())
                .collect();

            let full_param_str: String = handler.params.iter()
                .map(|p| format!("{}: {}", p.name, type_expr_to_native(&p.ty.node).rust_str()))
                .collect::<Vec<_>>()
                .join(", ");

            let other_args_str = if other_args.is_empty() {
                String::new()
            } else {
                format!(", {}", other_args.join(", "))
            };

            out.push_str(&format!(
                "#[no_mangle]\npub extern \"C\" fn {fn_name}_par({full_param_str}) -> {} {{\n\
                \tlet _n_threads = {threads_expr};\n\
                \tlet _total = {first_param} as usize;\n\
                \tif _total < _n_threads * 1000 {{\n\
                \t\treturn {fn_name}({first_param}{other_args_str});\n\
                \t}}\n\
                \tlet _chunk = (_total + _n_threads - 1) / _n_threads;\n\
                \tlet _result: f64 = std::thread::scope(|_s| {{\n\
                \t\tlet _handles: Vec<_> = (0.._n_threads).map(|_t| {{\n\
                \t\t\tlet _start = _t * _chunk;\n\
                \t\t\tlet _end = std::cmp::min((_t + 1) * _chunk, _total);\n\
                \t\t\tlet _chunk_n = (_end - _start) as i64;\n\
                \t\t\t_s.spawn(move || {{\n\
                \t\t\t\t{fn_name}(_chunk_n{other_args_str}) * _chunk_n as f64\n\
                \t\t\t}})\n\
                \t\t}}).collect();\n\
                \t\t_handles.into_iter().map(|h| h.join().unwrap()).sum::<f64>()\n\
                \t}});\n\
                \t(_result / {first_param} as f64) as {}\n\
                }}\n\n",
                ret_type.rust_str(), ret_type.rust_str()
            ));
        }

        let param_types: Vec<NativeType> = handler.params.iter()
            .map(|p| type_expr_to_native(&p.ty.node))
            .collect();

        // Use parallel version if available
        if is_parallel {
            if param_types.len() > 3 {
                // Generate array wrapper for the parallel version
                out.push_str(&format!("#[no_mangle]\npub extern \"C\" fn {}_par_arr(args: *const f64, _count: i64) -> f64 {{\n", fn_name));
                out.push_str("    unsafe {\n");
                let call_args: Vec<String> = handler.params.iter().enumerate().map(|(i, p)| {
                    let ty = type_expr_to_native(&p.ty.node);
                    match ty {
                        NativeType::Int => format!("*args.add({}) as i64", i),
                        NativeType::Float => format!("*args.add({})", i),
                        NativeType::Bool => format!("*args.add({}) != 0.0", i),
                    }
                }).collect();
                out.push_str(&format!("        let r = {}_par({});\n", fn_name, call_args.join(", ")));
                out.push_str("        r as f64\n    }\n}\n\n");
                sigs.push(NativeSig {
                    fn_name: format!("{}_par_arr", fn_name),
                    param_types: param_types.clone(),
                    return_type: ret_type,
                    uses_shared_args: false,
                });
            } else {
                sigs.push(NativeSig {
                    fn_name: format!("{}_par", fn_name),
                    param_types: param_types.clone(),
                    return_type: ret_type,
                    uses_shared_args: false,
                });
            }
        } else
        // For >3 params, generate an array-based wrapper
        if param_types.len() > 3 {
            out.push_str(&format!("#[no_mangle]\npub extern \"C\" fn {}_arr(args: *const f64, _count: i64) -> f64 {{\n", fn_name));
            out.push_str("    unsafe {\n");
            let call_args: Vec<String> = handler.params.iter().enumerate().map(|(i, p)| {
                let ty = type_expr_to_native(&p.ty.node);
                match ty {
                    NativeType::Int => format!("*args.add({}) as i64", i),
                    NativeType::Float => format!("*args.add({})", i),
                    NativeType::Bool => format!("*args.add({}) != 0.0", i),
                }
            }).collect();
            out.push_str(&format!("        let r = {}({});\n", fn_name, call_args.join(", ")));
            match ret_type {
                NativeType::Float => out.push_str("        r\n"),
                NativeType::Int => out.push_str("        r as f64\n"),
                NativeType::Bool => out.push_str("        if r { 1.0 } else { 0.0 }\n"),
            }
            out.push_str("    }\n}\n\n");

            // Use the array wrapper as the exported symbol
            sigs.push(NativeSig {
                fn_name: format!("{}_arr", fn_name),
                param_types,
                return_type: ret_type,
                uses_shared_args: false,
            });
        } else {
            let shared = ret_type == NativeType::Int;
            sigs.push(NativeSig {
                fn_name,
                param_types,
                return_type: ret_type,
                uses_shared_args: shared,
            });
        }
    }

    (out, sigs)
}

fn type_expr_to_native(ty: &TypeExpr) -> NativeType {
    match ty {
        TypeExpr::Simple(name) => match name.as_str() {
            "Int" => NativeType::Int,
            "Float" => NativeType::Float,
            "Bool" => NativeType::Bool,
            _ => NativeType::Float, // fallback
        },
        _ => NativeType::Float,
    }
}

struct FnGenerator {
    var_types: HashMap<String, NativeType>,
    siblings: HashSet<String>,
    fn_name_upper: Option<String>,
}

impl FnGenerator {
    fn new(params: &[Param], siblings: &HashSet<String>, fn_name: &str) -> Self {
        let mut var_types = HashMap::new();
        for p in params {
            var_types.insert(p.name.clone(), type_expr_to_native(&p.ty.node));
        }
        Self {
            var_types,
            siblings: siblings.clone(),
            fn_name_upper: Some(fn_name.to_uppercase()),
        }
    }

    fn infer_body_types(&mut self, body: &[Spanned<Statement>]) {
        for stmt in body {
            self.infer_stmt_types(&stmt.node);
        }
    }

    fn infer_stmt_types(&mut self, stmt: &Statement) {
        match stmt {
            Statement::Let { name, value } => {
                let ty = self.infer_expr_type(&value.node);
                self.var_types.insert(name.clone(), ty);
            }
            Statement::Assign { name, value } => {
                let ty = self.infer_expr_type(&value.node);
                // Assignment can promote int to float
                if let Some(existing) = self.var_types.get(name) {
                    if *existing == NativeType::Int && ty == NativeType::Float {
                        self.var_types.insert(name.clone(), NativeType::Float);
                    }
                } else {
                    self.var_types.insert(name.clone(), ty);
                }
            }
            Statement::If { then_body, else_body, .. } => {
                for s in then_body { self.infer_stmt_types(&s.node); }
                for s in else_body { self.infer_stmt_types(&s.node); }
            }
            Statement::While { body, .. } => {
                for s in body { self.infer_stmt_types(&s.node); }
            }
            Statement::For { var, iter, body, .. } => {
                // for var in range(...) → var is Int
                self.var_types.insert(var.clone(), NativeType::Int);
                let _ = self.infer_expr_type(&iter.node);
                for s in body { self.infer_stmt_types(&s.node); }
            }
            _ => {}
        }
    }

    fn infer_expr_type(&self, expr: &Expr) -> NativeType {
        match expr {
            Expr::Literal(Literal::Int(_)) => NativeType::Int,
            Expr::Literal(Literal::Float(_)) => NativeType::Float,
            Expr::Literal(Literal::Bool(_)) => NativeType::Bool,
            Expr::Ident(name) => {
                self.var_types.get(name).copied().unwrap_or(NativeType::Float)
            }
            Expr::BinaryOp { left, op, right } => {
                let lt = self.infer_expr_type(&left.node);
                let rt = self.infer_expr_type(&right.node);
                match op {
                    BinOp::Div => {
                        // Int/Int → Int (floor division), otherwise Float
                        if lt == NativeType::Int && rt == NativeType::Int {
                            NativeType::Int
                        } else {
                            NativeType::Float
                        }
                    }
                    BinOp::And | BinOp::Or => NativeType::Bool,
                    _ => {
                        if lt == NativeType::Float || rt == NativeType::Float {
                            NativeType::Float
                        } else {
                            lt // both Int → Int, both Bool → Bool
                        }
                    }
                }
            }
            Expr::CmpOp { .. } => NativeType::Bool,
            Expr::Not(_) => NativeType::Bool,
            Expr::FnCall { name, .. } => {
                match name.as_str() {
                    "random" | "sqrt" | "log" | "exp" | "pow" | "sin" | "cos" => NativeType::Float,
                    "len" | "floor" | "ceil" | "round" => NativeType::Int,
                    "abs" | "min" | "max" => {
                        // Depends on args, default to float
                        NativeType::Float
                    }
                    _ => NativeType::Float,
                }
            }
            _ => NativeType::Float,
        }
    }

    fn infer_return_type(&self, body: &[Spanned<Statement>]) -> NativeType {
        // Find the first return statement and infer from its expression
        for stmt in body {
            match &stmt.node {
                Statement::Return { value } => {
                    return self.infer_expr_type(&value.node);
                }
                Statement::If { then_body, else_body, .. } => {
                    if let Some(ty) = self.find_return_type(then_body) {
                        return ty;
                    }
                    if let Some(ty) = self.find_return_type(else_body) {
                        return ty;
                    }
                }
                _ => {}
            }
        }
        // No explicit return — check last expression
        if let Some(last) = body.last() {
            if let Statement::ExprStmt { expr } = &last.node {
                return self.infer_expr_type(&expr.node);
            }
        }
        NativeType::Float // default
    }

    fn find_return_type(&self, body: &[Spanned<Statement>]) -> Option<NativeType> {
        for stmt in body {
            if let Statement::Return { value } = &stmt.node {
                return Some(self.infer_expr_type(&value.node));
            }
        }
        None
    }

    fn indent(level: usize) -> String {
        "    ".repeat(level)
    }

    fn gen_stmt(&self, stmt: &Statement, indent: usize) -> String {
        let ind = Self::indent(indent);
        match stmt {
            Statement::Let { name, value } => {
                let ty = self.var_types.get(name).copied().unwrap_or(NativeType::Float);
                let expr = self.gen_expr(&value.node, ty);
                format!("{}let mut {}: {} = {};\n", ind, name, ty.compute_str(), expr)
            }
            Statement::Assign { name, value } => {
                let ty = self.var_types.get(name).copied().unwrap_or(NativeType::Float);
                let expr = self.gen_expr(&value.node, ty);
                format!("{}{} = {};\n", ind, name, expr)
            }
            Statement::Return { value } => {
                let ret_ty = self.infer_expr_type(&value.node);
                let expr = self.gen_expr(&value.node, ret_ty);
                if ret_ty == NativeType::Int {
                    let upper = self.fn_name_upper.as_deref().unwrap_or("UNKNOWN");
                    let mut s = String::new();
                    s.push_str(&format!("{}let _ret_val = {};\n", ind, expr));
                    s.push_str(&format!("{}use num_traits::ToPrimitive;\n", ind));
                    s.push_str(&format!("{}match _ret_val.to_i64() {{\n", ind));
                    s.push_str(&format!("{}    Some(v) => return v,\n", ind));
                    s.push_str(&format!("{}    None => {{\n", ind));
                    s.push_str(&format!("{}        unsafe {{ _SOMA_RESULT = Some(_ret_val.to_string()); }}\n", ind));
                    s.push_str(&format!("{}        return i64::MIN;\n", ind));
                    s.push_str(&format!("{}    }}\n", ind));
                    s.push_str(&format!("{}}}\n", ind));
                    s
                } else {
                    format!("{}return {};\n", ind, expr)
                }
            }
            Statement::If { condition, then_body, else_body } => {
                let cond = self.gen_expr(&condition.node, NativeType::Bool);
                let mut s = format!("{}if {} {{\n", ind, cond);
                for st in then_body {
                    s.push_str(&self.gen_stmt(&st.node, indent + 1));
                }
                if else_body.is_empty() {
                    s.push_str(&format!("{}}}\n", ind));
                } else {
                    s.push_str(&format!("{}}} else {{\n", ind));
                    for st in else_body {
                        s.push_str(&self.gen_stmt(&st.node, indent + 1));
                    }
                    s.push_str(&format!("{}}}\n", ind));
                }
                s
            }
            Statement::While { condition, body } => {
                let cond = self.gen_expr(&condition.node, NativeType::Bool);
                let mut s = format!("{}while {} {{\n", ind, cond);
                for st in body {
                    s.push_str(&self.gen_stmt(&st.node, indent + 1));
                }
                s.push_str(&format!("{}}}\n", ind));
                s
            }
            Statement::For { var, iter, body } => {
                let iter_code = self.gen_for_iter(&iter.node);
                let mut s = format!("{}for {} in {} {{\n", ind, var, iter_code);
                for st in body {
                    s.push_str(&self.gen_stmt(&st.node, indent + 1));
                }
                s.push_str(&format!("{}}}\n", ind));
                s
            }
            Statement::Break => format!("{}break;\n", ind),
            Statement::Continue => format!("{}continue;\n", ind),
            Statement::ExprStmt { expr } => {
                let code = self.gen_expr(&expr.node, NativeType::Float);
                format!("{}{};\n", ind, code)
            }
            _ => format!("{}// unsupported statement\n", ind),
        }
    }

    fn gen_for_iter(&self, expr: &Expr) -> String {
        // range(a, b) → a..b
        if let Expr::FnCall { name, args } = expr {
            if name == "range" && args.len() == 2 {
                let a = self.gen_expr(&args[0].node, NativeType::Int);
                let b = self.gen_expr(&args[1].node, NativeType::Int);
                return format!("{}..{}", a, b);
            }
        }
        // Fallback
        format!("0..0 /* unsupported iterator */")
    }

    fn gen_expr(&self, expr: &Expr, target_ty: NativeType) -> String {
        match expr {
            Expr::Literal(Literal::Int(n)) => {
                if target_ty == NativeType::Float {
                    format!("{}.0f64", n)
                } else {
                    format!("BigInt::from({}i64)", n)
                }
            }
            Expr::Literal(Literal::Float(f)) => format!("{}f64", f),
            Expr::Literal(Literal::Bool(b)) => format!("{}", b),
            Expr::Ident(name) => {
                let var_ty = self.var_types.get(name).copied().unwrap_or(NativeType::Float);
                if target_ty == NativeType::Float && var_ty == NativeType::Int {
                    format!("{}.to_i64().unwrap_or(0) as f64", name)
                } else if target_ty == NativeType::Int && var_ty == NativeType::Float {
                    format!("BigInt::from({} as i64)", name)
                } else if var_ty == NativeType::Int {
                    // Use reference to avoid cloning BigInt
                    format!("(&{})", name)
                } else {
                    name.clone()
                }
            }
            Expr::BinaryOp { left, op, right } => {
                let result_ty = self.infer_expr_type(expr);
                let lt = self.infer_expr_type(&left.node);
                let rt = self.infer_expr_type(&right.node);

                match op {
                    BinOp::Div => {
                        if lt == NativeType::Int && rt == NativeType::Int {
                            // Integer division via V type (BigInt-safe)
                            let l = self.gen_expr(&left.node, NativeType::Int);
                            let r = self.gen_expr(&right.node, NativeType::Int);
                            format!("({} / {})", l, r)
                        } else {
                            // Float division
                            let l = self.gen_expr(&left.node, NativeType::Float);
                            let r = self.gen_expr(&right.node, NativeType::Float);
                            let inner = format!("({} / {})", l, r);
                            if target_ty == NativeType::Int {
                                format!("({} as i128)", inner)
                            } else {
                                inner
                            }
                        }
                    }
                    BinOp::Mod => {
                        // Modulo: keep types consistent
                        let common = if lt == NativeType::Float || rt == NativeType::Float {
                            NativeType::Float
                        } else {
                            NativeType::Int
                        };
                        let l = self.gen_expr(&left.node, common);
                        let r = self.gen_expr(&right.node, common);
                        format!("({} % {})", l, r)
                    }
                    BinOp::And => {
                        let l = self.gen_expr(&left.node, NativeType::Bool);
                        let r = self.gen_expr(&right.node, NativeType::Bool);
                        format!("({} && {})", l, r)
                    }
                    BinOp::Or => {
                        let l = self.gen_expr(&left.node, NativeType::Bool);
                        let r = self.gen_expr(&right.node, NativeType::Bool);
                        format!("({} || {})", l, r)
                    }
                    _ => {
                        let common = if lt == NativeType::Float || rt == NativeType::Float {
                            NativeType::Float
                        } else {
                            result_ty
                        };
                        let l = self.gen_expr(&left.node, common);
                        let r = self.gen_expr(&right.node, common);
                        let op_str = match op { BinOp::Add => "+", BinOp::Sub => "-", BinOp::Mul => "*", _ => unreachable!() };
                        let inner = format!("({} {} {})", l, op_str, r);
                        // Coerce to target if needed
                        if target_ty == NativeType::Float && common == NativeType::Int {
                            format!("({} as f64)", inner)
                        } else if target_ty == NativeType::Int && common == NativeType::Float {
                            format!("({} as i128)", inner)
                        } else {
                            inner
                        }
                    }
                }
            }
            Expr::CmpOp { left, op, right } => {
                // Compare in the wider type
                let lt = self.infer_expr_type(&left.node);
                let rt = self.infer_expr_type(&right.node);
                let common = if lt == NativeType::Float || rt == NativeType::Float {
                    NativeType::Float
                } else {
                    NativeType::Int
                };
                let l = self.gen_expr(&left.node, common);
                let r = self.gen_expr(&right.node, common);
                let op_str = match op {
                    CmpOp::Lt => "<",
                    CmpOp::Gt => ">",
                    CmpOp::Le => "<=",
                    CmpOp::Ge => ">=",
                    CmpOp::Eq => "==",
                    CmpOp::Ne => "!=",
                };
                format!("({} {} {})", l, op_str, r)
            }
            Expr::Not(inner) => {
                let e = self.gen_expr(&inner.node, NativeType::Bool);
                format!("(!{})", e)
            }
            Expr::FnCall { name, args } => {
                self.gen_fn_call(name, args, target_ty)
            }
            Expr::Pipe { left, right } => {
                self.gen_pipe(&left.node, &right.node, target_ty)
            }
            Expr::Lambda { param, body } => {
                // Inline lambda: |param| { body }
                let body_code = self.gen_expr(&body.node, NativeType::Float);
                format!("|{}| {{ {} }}", param, body_code)
            }
            Expr::LambdaBlock { param, stmts, result } => {
                let mut code = format!("|{}| {{\n", param);
                for stmt in stmts {
                    code.push_str(&self.gen_stmt(&stmt.node, 2));
                }
                code.push_str(&format!("        {}\n    }}", self.gen_expr(&result.node, NativeType::Float)));
                code
            }
            Expr::ListLiteral(elements) => {
                let items: Vec<String> = elements.iter().map(|e| self.gen_expr(&e.node, target_ty)).collect();
                format!("vec![{}]", items.join(", "))
            }
            Expr::FieldAccess { target, field } => {
                // For lambda params accessing map fields — in native, these are struct fields
                // For now, treat as tuple access or direct field
                let t = self.gen_expr(&target.node, target_ty);
                format!("{}.{}", t, field)
            }
            _ => "/* unsupported expr */ 0".to_string(),
        }
    }

    fn gen_fn_call(&self, name: &str, args: &[Spanned<Expr>], target_ty: NativeType) -> String {
        match name {
            "random" => {
                "unsafe { _soma_random() }".to_string()
            }
            "sqrt" => {
                let a = self.gen_expr(&args[0].node, NativeType::Float);
                format!("({}).sqrt()", a)
            }
            "log" => {
                let a = self.gen_expr(&args[0].node, NativeType::Float);
                format!("({}).ln()", a)
            }
            "exp" => {
                let a = self.gen_expr(&args[0].node, NativeType::Float);
                format!("({}).exp()", a)
            }
            "pow" => {
                let a = self.gen_expr(&args[0].node, NativeType::Float);
                let b = self.gen_expr(&args[1].node, NativeType::Float);
                format!("({}).powf({})", a, b)
            }
            "abs" => {
                let a_ty = self.infer_expr_type(&args[0].node);
                let a = self.gen_expr(&args[0].node, a_ty);
                format!("({}).abs()", a)
            }
            "min" => {
                if args.len() == 2 {
                    let a_ty = self.infer_expr_type(&args[0].node);
                    let b_ty = self.infer_expr_type(&args[1].node);
                    let common = if a_ty == NativeType::Float || b_ty == NativeType::Float {
                        NativeType::Float
                    } else {
                        NativeType::Int
                    };
                    let a = self.gen_expr(&args[0].node, common);
                    let b = self.gen_expr(&args[1].node, common);
                    if common == NativeType::Float {
                        format!("({}).min({})", a, b) // f64::min
                    } else {
                        format!("std::cmp::min({}, {})", a, b)
                    }
                } else {
                    "0".to_string()
                }
            }
            "max" => {
                if args.len() == 2 {
                    let a_ty = self.infer_expr_type(&args[0].node);
                    let b_ty = self.infer_expr_type(&args[1].node);
                    let common = if a_ty == NativeType::Float || b_ty == NativeType::Float {
                        NativeType::Float
                    } else {
                        NativeType::Int
                    };
                    let a = self.gen_expr(&args[0].node, common);
                    let b = self.gen_expr(&args[1].node, common);
                    if common == NativeType::Float {
                        format!("({}).max({})", a, b)
                    } else {
                        format!("std::cmp::max({}, {})", a, b)
                    }
                } else {
                    "0".to_string()
                }
            }
            "floor" => {
                let a = self.gen_expr(&args[0].node, NativeType::Float);
                format!("BigInt::from(({}).floor() as i64)", a)
            }
            "ceil" => {
                let a = self.gen_expr(&args[0].node, NativeType::Float);
                format!("BigInt::from(({}).ceil() as i64)", a)
            }
            "round" => {
                let a = self.gen_expr(&args[0].node, NativeType::Float);
                format!("BigInt::from(({}).round() as i64)", a)
            }
            "sin" => {
                let a = self.gen_expr(&args[0].node, NativeType::Float);
                format!("({}).sin()", a)
            }
            "cos" => {
                let a = self.gen_expr(&args[0].node, NativeType::Float);
                format!("({}).cos()", a)
            }
            "len" => {
                let a = self.gen_expr(&args[0].node, NativeType::Int);
                format!("BigInt::from(0i64)") // simplified — lists not yet supported in codegen
            }
            "nth" => {
                format!("/* nth */ 0") // simplified
            }
            "range" => {
                // Used in for loops, shouldn't appear as expression
                if args.len() == 2 {
                    let a = self.gen_expr(&args[0].node, NativeType::Int);
                    let b = self.gen_expr(&args[1].node, NativeType::Int);
                    format!("({}..{})", a, b)
                } else {
                    "(0..0)".to_string()
                }
            }
            other => {
                // Call to another native handler in the same cell
                let arg_strs: Vec<String> = args.iter()
                    .map(|a| {
                        let ty = self.infer_expr_type(&a.node);
                        self.gen_expr(&a.node, ty)
                    })
                    .collect();
                format!("handler_{}({})", other, arg_strs.join(", "))
            }
        }
    }

    /// Generate parallel Rust code for pipe expressions.
    /// range(0, n) |> map(f) |> reduce(init, f) → parallel iteration
    /// Flatten a pipe chain into: (source, [(op_name, args), ...], optional_suffix_expr)
    fn flatten_pipe<'a>(&self, expr: &'a Expr) -> (String, Vec<(&'a str, &'a [Spanned<Expr>])>) {
        match expr {
            Expr::Pipe { left, right } => {
                let (source, mut ops) = self.flatten_pipe(&left.node);
                match &right.node {
                    Expr::FnCall { name, args } => {
                        ops.push((name.as_str(), args.as_slice()));
                    }
                    // Handle: pipe |> reduce(...) / n — arithmetic wrapping a pipe op
                    Expr::BinaryOp { left: inner_left, .. } => {
                        if let Expr::FnCall { name, args } = &inner_left.node {
                            ops.push((name.as_str(), args.as_slice()));
                        }
                        // The arithmetic (/ n * 4.0) will be handled by the BinaryOp in gen_expr
                        // since we only flatten the pipe part
                    }
                    _ => {}
                }
                (source, ops)
            }
            Expr::FnCall { name, args } if name == "range" && args.len() == 2 => {
                let a = self.gen_expr(&args[0].node, NativeType::Int);
                let b = self.gen_expr(&args[1].node, NativeType::Int);
                (format!("({}..{})", a, b), Vec::new())
            }
            other => (self.gen_expr(other, NativeType::Float), Vec::new()),
        }
    }

    fn gen_pipe(&self, left: &Expr, right: &Expr, _target_ty: NativeType) -> String {
        // Collect: pipe source + right-side operation
        let (source, mut ops) = self.flatten_pipe(left);

        // Extract the FnCall from right — it may be wrapped in nested BinaryOps
        // e.g., reduce(0.0, f) / n * 4.0 → BinaryOp(BinaryOp(reduce, Div, n), Mul, 4.0)
        let mut suffix = String::new();
        let mut current = right;
        // Peel off BinaryOps from outside-in, collecting suffix operations
        let mut suffix_ops: Vec<(BinOp, String)> = Vec::new();
        loop {
            match current {
                Expr::FnCall { name, args } => {
                    ops.push((name.as_str(), args.as_slice()));
                    break;
                }
                Expr::BinaryOp { left: inner, op, right: rhs } => {
                    let op_str = match op {
                        BinOp::Add => "+", BinOp::Sub => "-", BinOp::Mul => "*",
                        BinOp::Div => "/", BinOp::Mod => "%", _ => "+",
                    };
                    let rhs_code = self.gen_expr(&rhs.node, NativeType::Float);
                    suffix_ops.push((*op, rhs_code));
                    current = &inner.node;
                }
                _ => break,
            }
        }
        // Build suffix from innermost to outermost
        for (op, rhs) in suffix_ops.iter().rev() {
            let op_str = match op {
                BinOp::Add => "+", BinOp::Sub => "-", BinOp::Mul => "*",
                BinOp::Div => "/", BinOp::Mod => "%", _ => "+",
            };
            suffix = format!("{} {} {}", suffix, op_str, rhs);
        }

        // Build a Rust iterator chain
        let mut chain = source;

        for (op_name, args) in &ops {
            match *op_name {
                "map" if args.len() == 1 => {
                    let lambda_body = self.gen_map_lambda(&args[0].node);
                    // Extract the lambda param name
                    let param_name = match &args[0].node {
                        Expr::Lambda { param, .. } | Expr::LambdaBlock { param, .. } => param.clone(),
                        _ => "_i".to_string(),
                    };
                    chain = format!("({}).map(|{}| -> f64 {{ {} }})", chain, param_name, lambda_body);
                }
                "filter" if args.len() == 1 => {
                    let lambda_body = self.gen_expr(&args[0].node, NativeType::Bool);
                    chain = format!("({}).filter({})", chain, lambda_body);
                }
                "reduce" | "fold" if args.len() == 2 => {
                    let mut init = self.gen_expr(&args[0].node, NativeType::Float);
                    // Avoid double suffix like 0f64f64
                    if !init.ends_with("f64") { init = format!("{}f64", init); }
                    let fold_body = self.gen_reduce_lambda(&args[1].node);
                    chain = format!("({}).fold({}, |_acc, _val| {{ let _val = _val as f64; {} }})", chain, init, fold_body);
                }
                _ => {
                    chain = format!("/* unknown pipe op: {} */ {}", op_name, chain);
                }
            }
        }

        // Check if the chain ends with a fold (returns f64) or a map (returns iterator)
        let last_op = ops.last().map(|(name, _)| *name).unwrap_or("");
        if last_op != "reduce" && last_op != "fold" {
            chain = format!("({}).collect::<Vec<f64>>()", chain);
        }

        // Apply suffix arithmetic (e.g., / n * 4.0)
        if !suffix.is_empty() {
            chain = format!("({}{})", chain, suffix);
        }

        chain
    }

    /// Generate the body of a map lambda for native pipes.
    /// Handles both simple lambdas and block lambdas.
    fn gen_map_lambda(&self, expr: &Expr) -> String {
        match expr {
            Expr::Lambda { param: _, body } => {
                // The lambda body — generate as Rust expression
                self.gen_map_lambda_body(&body.node)
            }
            Expr::LambdaBlock { param: _, stmts, result } => {
                let mut code = String::new();
                for stmt in stmts {
                    code.push_str(&self.gen_stmt(&stmt.node, 3));
                }
                code.push_str(&format!("{}", self.gen_map_lambda_body(&result.node)));
                code
            }
            _ => "0.0f64".to_string(),
        }
    }

    fn gen_map_lambda_body(&self, expr: &Expr) -> String {
        match expr {
            Expr::FnCall { name, args } => {
                // Call to another native handler or builtin
                self.gen_fn_call(name, args, NativeType::Float)
            }
            Expr::BinaryOp { left, op, right } => {
                let l = self.gen_map_lambda_body(&left.node);
                let r = self.gen_map_lambda_body(&right.node);
                let op_str = match op {
                    BinOp::Add => "+", BinOp::Sub => "-", BinOp::Mul => "*",
                    BinOp::Div => "/", BinOp::Mod => "%", _ => "+",
                };
                format!("({} {} {})", l, op_str, r)
            }
            Expr::Literal(Literal::Float(f)) => format!("{}f64", f),
            Expr::Literal(Literal::Int(n)) => format!("{}f64", n),
            Expr::Ident(name) => format!("{} as f64", name),
            _ => self.gen_expr(expr, NativeType::Float),
        }
    }

    /// Translate a reduce lambda (p => p.acc + p.val) into Rust fold body
    /// The lambda parameter accesses .acc and .val — we replace with _acc and _val
    fn gen_reduce_lambda(&self, expr: &Expr) -> String {
        match expr {
            Expr::Lambda { param, body } => {
                // Replace param.acc → _acc, param.val → _val in the body
                self.gen_reduce_body(&body.node, param)
            }
            Expr::LambdaBlock { param, stmts: _, result } => {
                self.gen_reduce_body(&result.node, param)
            }
            _ => "_acc + _val".to_string(),
        }
    }

    fn gen_reduce_body(&self, expr: &Expr, param: &str) -> String {
        match expr {
            Expr::BinaryOp { left, op, right } => {
                let l = self.gen_reduce_body(&left.node, param);
                let r = self.gen_reduce_body(&right.node, param);
                let op_str = match op {
                    BinOp::Add => "+",
                    BinOp::Sub => "-",
                    BinOp::Mul => "*",
                    BinOp::Div => "/",
                    BinOp::Mod => "%",
                    _ => "+",
                };
                format!("({} {} {})", l, op_str, r)
            }
            Expr::FieldAccess { target, field } => {
                if let Expr::Ident(name) = &target.node {
                    if name == param {
                        match field.as_str() {
                            "acc" => "_acc".to_string(),
                            "val" => "_val".to_string(),
                            _ => format!("/* unknown field {} */", field),
                        }
                    } else {
                        format!("{}.{}", name, field)
                    }
                } else {
                    "_acc".to_string()
                }
            }
            Expr::Ident(name) => name.clone(),
            Expr::Literal(Literal::Int(n)) => format!("{}i64 as f64", n),
            Expr::Literal(Literal::Float(f)) => format!("{}f64", f),
            Expr::FnCall { name, args } => {
                self.gen_fn_call(name, args, NativeType::Float)
            }
            _ => "_acc + _val".to_string(),
        }
    }
}

/// Check if a handler body uses random() anywhere
fn body_uses_random(body: &[Spanned<Statement>]) -> bool {
    body.iter().any(|s| stmt_uses_random(&s.node))
}

fn stmt_uses_random(stmt: &Statement) -> bool {
    match stmt {
        Statement::Let { value, .. } | Statement::Assign { value, .. } | Statement::Return { value } => {
            expr_uses_random(&value.node)
        }
        Statement::If { condition, then_body, else_body } => {
            expr_uses_random(&condition.node) || body_uses_random(then_body) || body_uses_random(else_body)
        }
        Statement::While { condition, body } => {
            expr_uses_random(&condition.node) || body_uses_random(body)
        }
        Statement::For { iter, body, .. } => {
            expr_uses_random(&iter.node) || body_uses_random(body)
        }
        Statement::ExprStmt { expr } => expr_uses_random(&expr.node),
        _ => false,
    }
}

fn expr_uses_random(expr: &Expr) -> bool {
    match expr {
        Expr::FnCall { name, args } => {
            name == "random" || args.iter().any(|a| expr_uses_random(&a.node))
        }
        Expr::BinaryOp { left, right, .. } | Expr::CmpOp { left, right, .. } => {
            expr_uses_random(&left.node) || expr_uses_random(&right.node)
        }
        Expr::Not(inner) => expr_uses_random(&inner.node),
        _ => false,
    }
}


/// Transform generated BigInt-style arithmetic to V-type in-place ops.
/// Patterns:
///   x = ((&x) * (&y));     → x.mul_v(&y);
///   x = ((&x) + V::S(1));  → x.add(1);
///   x = ((&x) + (&y));     → x.add_v(&y);
///   x = ((&x) - (&y));     → x.sub_v(&y);
///   Also handles: let t = (&b) patterns for temp variables
fn transform_v_arithmetic(code: &str) -> String {
    let mut result = String::new();
    for line in code.lines() {
        let trimmed = line.trim();
        // Pattern: x = ((&x) OP (&y));
        if let Some(eq_pos) = trimmed.find(" = ") {
            let lhs = trimmed[..eq_pos].trim();
            let rhs = trimmed[eq_pos + 3..].trim().trim_end_matches(';');

            // x = ((&x) + V::S(N)); → x.add(N);
            if let Some(rest) = rhs.strip_prefix(&format!("((&{}) + V::S(", lhs)) {
                if let Some(n) = rest.strip_suffix("))") {
                    result.push_str(&format!("{}{};\n", &line[..line.len()-trimmed.len()],
                        format!("{}.add({})", lhs, n)));
                    continue;
                }
            }
            if let Some(rest) = rhs.strip_prefix(&format!("((&{}) - V::S(", lhs)) {
                if let Some(n) = rest.strip_suffix("))") {
                    result.push_str(&format!("{}{};\n", &line[..line.len()-trimmed.len()],
                        format!("{}.sub({})", lhs, n)));
                    continue;
                }
            }

            // x = ((&x) * (&y)); → x.mul_v(&y);
            if let Some(rest) = rhs.strip_prefix(&format!("((&{}) * (&", lhs)) {
                if let Some(y) = rest.strip_suffix("))") {
                    result.push_str(&format!("{}{};\n", &line[..line.len()-trimmed.len()],
                        format!("{}.mul_v(&{})", lhs, y)));
                    continue;
                }
            }
            // x = ((&x) + (&y)); → x.add_v(&y);
            if let Some(rest) = rhs.strip_prefix(&format!("((&{}) + (&", lhs)) {
                if let Some(y) = rest.strip_suffix("))") {
                    result.push_str(&format!("{}{};\n", &line[..line.len()-trimmed.len()],
                        format!("{}.add_v(&{})", lhs, y)));
                    continue;
                }
            }
            // x = ((&x) - (&y)); → x.sub_v(&y);
            if let Some(rest) = rhs.strip_prefix(&format!("((&{}) - (&", lhs)) {
                if let Some(y) = rest.strip_suffix("))") {
                    result.push_str(&format!("{}{};\n", &line[..line.len()-trimmed.len()],
                        format!("{}.sub_v(&{})", lhs, y)));
                    continue;
                }
            }

            // let x: V = (&y);  →  let x: V = y.clone_v();
            if trimmed.starts_with("let ") && rhs.starts_with("(&") && rhs.ends_with(")") {
                let var = &rhs[2..rhs.len()-1];
                result.push_str(&format!("{}{} = {}.clone_v();\n", &line[..line.len()-trimmed.len()], &trimmed[..eq_pos], var));
                continue;
            }

            // x = (&y); → x = y.clone_v();
            if rhs.starts_with("(&") && rhs.ends_with(")") {
                let var = &rhs[2..rhs.len()-1];
                result.push_str(&format!("{}{} = {}.clone_v();\n", &line[..line.len()-trimmed.len()], lhs, var));
                continue;
            }
        }

        // while ((&i) <= (&n)) → while i.le_v(n) (if n is param)
        // while ((&i) < (&n)) → while i.lt_v(n)
        if trimmed.starts_with("while ") {
            let cond = trimmed.strip_prefix("while ").unwrap().trim_end_matches(" {").trim();
            if let Some(rest) = cond.strip_prefix("((&") {
                if let Some(inner) = rest.strip_suffix("))") {
                    if inner.contains(") <= (&") {
                        let parts: Vec<&str> = inner.splitn(2, ") <= (&").collect();
                        if parts.len() == 2 {
                            let indent = &line[..line.len()-trimmed.len()];
                            result.push_str(&format!("{}while {}.le_v(&{}) {{\n", indent, parts[0], parts[1]));
                            continue;
                        }
                    }
                    if inner.contains(") < (&") {
                        let parts: Vec<&str> = inner.splitn(2, ") < (&").collect();
                        if parts.len() == 2 {
                            let indent = &line[..line.len()-trimmed.len()];
                            result.push_str(&format!("{}while {}.lt_v(&{}) {{\n", indent, parts[0], parts[1]));
                            continue;
                        }
                    }
                }
            }
        }

        // Return: convert V to i64 or write BigInt buffer
        if trimmed.contains("_ret_val.to_i64()") {
            let line = line.replace("_ret_val.to_i64()", "_ret_val.to_i64()");
            result.push_str(&line);
            result.push('\n');
            continue;
        }

        // General: x = ((&y) OP (&z)); where OP is +,-,*
        if let Some(eq_pos) = trimmed.find(" = ") {
            let lhs = trimmed[..eq_pos].trim();
            let rhs = trimmed[eq_pos + 3..].trim().trim_end_matches(';');
            if rhs.starts_with("((&") && rhs.ends_with("))") {
                let inner = &rhs[1..rhs.len()-1]; // strip outer parens
                let mut matched = false;
                for (op_str, method) in [(" + ", "add_v"), (" - ", "sub_v"), (" * ", "mul_v"), (" / ", "div_v"), (" % ", "mod_v")] {
                    if let Some(pos) = inner.find(op_str) {
                        let left = inner[..pos].trim().trim_start_matches("(&").trim_end_matches(')');
                        let right = inner[pos+op_str.len()..].trim().trim_start_matches("(&").trim_end_matches(')');
                        let indent = &line[..line.len()-trimmed.len()];
                        // If lhs is a `let` binding, emit without wrapping block
                        // so the variable stays in the enclosing scope
                        if lhs.contains("let ") {
                            result.push_str(&format!("{}let mut _t = {}.clone_v(); _t.{}(&{}); {} = _t;\n",
                                indent, left, method, right, lhs));
                        } else {
                            result.push_str(&format!("{}{{ let mut _t = {}.clone_v(); _t.{}(&{}); {} = _t; }}\n",
                                indent, left, method, right, lhs));
                        }
                        matched = true;
                        break;
                    }
                }
                if matched { continue; }
            }
        }

        result.push_str(line);
        result.push('\n');
    }
    result
}
