//! Generates Rust source from [native] handler AST.
//!
//! Two codegen modes:
//!   - **Direct**: Int=i64, Float=f64, Bool=bool. Direct C ABI. Fast for
//!     bounded-range numerics (Monte Carlo, fib(90), counters, etc.).
//!   - **Rug**: Int=rug::Integer. Shared buffer FFI. For BigInt-heavy
//!     workloads (PI spigot, arbitrary precision).
//!
//! Mode selection: handlers that return `String` use Rug mode (the canonical
//! "BigInt-as-string" output pattern). Everything else uses Direct mode.

use crate::ast::*;
use std::collections::{HashMap, HashSet};

// ── Public API ──────────────────────────────────────────────────────

/// Type inferred for a local variable
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum NativeType {
    Int,
    Float,
    Bool,
    String,
}

impl NativeType {
    fn rust_str(&self) -> &'static str {
        match self {
            NativeType::Int => "i64",
            NativeType::Float => "f64",
            NativeType::Bool => "bool",
            NativeType::String => "String",
        }
    }
}

/// Information about a native handler to be compiled
pub struct NativeHandler {
    pub cell_name: String,
    pub signal_name: String,
    pub params: Vec<Param>,
    pub body: Vec<Spanned<Statement>>,
}

/// FFI signature info: param types + return type
#[derive(Debug, Clone)]
pub struct NativeSig {
    pub fn_name: String,
    pub param_types: Vec<NativeType>,
    pub return_type: NativeType,
    /// If true, args are passed via shared buffer (_soma_push_*), not C params
    pub uses_shared_args: bool,
}

/// Parallel configuration for code generation
#[derive(Debug, Clone, Default)]
pub struct ParallelConfig {
    pub enabled: bool,
    pub handlers: Vec<String>,
    pub threads: usize,
}

/// Codegen mode for a single handler
#[derive(Debug, Clone, Copy, PartialEq)]
enum Mode {
    /// Int=i64, Float=f64, Bool=bool. Direct C ABI.
    Direct,
    /// Int=rug::Integer. Shared buffer FFI.
    Rug,
}

/// Generate Rust source for a set of native handlers in one cell.
pub fn generate_native_source(handlers: &[NativeHandler]) -> (String, Vec<NativeSig>) {
    generate_native_source_with_config(handlers, &ParallelConfig::default())
}

pub fn generate_native_source_with_config(
    handlers: &[NativeHandler],
    parallel: &ParallelConfig,
) -> (String, Vec<NativeSig>) {
    let mut out = String::new();
    let mut sigs = Vec::new();

    let siblings: HashSet<String> = handlers.iter().map(|h| h.signal_name.clone()).collect();

    // Decide mode for each handler
    let modes: Vec<Mode> = handlers.iter().map(|h| select_mode(h, &siblings)).collect();
    let any_rug = modes.iter().any(|m| *m == Mode::Rug);
    let uses_random = handlers.iter().any(|h| body_uses_random(&h.body));

    // ── Preamble ──
    out.push_str("// Generated by Soma compiler — [native] handlers\n");
    out.push_str("// Do not edit — regenerate from .cell source\n\n");

    if any_rug {
        out.push_str("use rug::Integer;\n");
        out.push_str("use rug::Assign;\n\n");
    }

    if uses_random {
        out.push_str("static mut _SOMA_RNG_STATE: u64 = 0x12345678_9abcdef0;\n\n");
        out.push_str("#[inline(always)]\nunsafe fn _soma_random() -> f64 {\n");
        out.push_str("    _SOMA_RNG_STATE ^= _SOMA_RNG_STATE >> 12;\n");
        out.push_str("    _SOMA_RNG_STATE ^= _SOMA_RNG_STATE << 25;\n");
        out.push_str("    _SOMA_RNG_STATE ^= _SOMA_RNG_STATE >> 27;\n");
        out.push_str("    let r = _SOMA_RNG_STATE.wrapping_mul(0x2545F4914F6CDD1D);\n");
        out.push_str("    (r >> 11) as f64 / ((1u64 << 53) as f64)\n");
        out.push_str("}\n\n");
    }

    // ── Shared buffer for Rug mode ──
    if any_rug {
        out.push_str(SHARED_BUFFER_RUG);
    }

    // ── Per-handler codegen ──
    for (handler, mode) in handlers.iter().zip(modes.iter()) {
        let mut gen = FnGenerator::new(&handler.params, &siblings, *mode);
        for p in &handler.params {
            gen.var_types.insert(p.name.clone(), type_expr_to_native(&p.ty.node));
        }
        gen.infer_body_types(&handler.body);
        let int_params: HashSet<String> = handler.params.iter()
            .filter(|p| type_expr_to_native(&p.ty.node) == NativeType::Int)
            .map(|p| p.name.clone())
            .collect();
        gen.classify_int_vars(&handler.body, &int_params);

        let fn_name = format!("handler_{}", handler.signal_name);
        let ret_type = gen.infer_return_type(&handler.body);

        match mode {
            Mode::Direct => {
                gen_direct_handler(&mut out, &gen, handler, &fn_name, ret_type);
            }
            Mode::Rug => {
                gen_rug_handler(&mut out, &gen, handler, &fn_name);
            }
        }

        // Build sig + optional parallel/array wrappers
        let param_types: Vec<NativeType> = handler.params.iter()
            .map(|p| type_expr_to_native(&p.ty.node))
            .collect();

        let is_parallel = parallel.enabled && parallel.handlers.contains(&handler.signal_name);
        if is_parallel && !handler.params.is_empty() && *mode == Mode::Direct {
            emit_parallel_wrapper(&mut out, handler, &fn_name, ret_type, parallel);
        }

        match mode {
            Mode::Rug => {
                // Rug handlers always go through shared buffer
                sigs.push(NativeSig {
                    fn_name,
                    param_types,
                    return_type: ret_type,
                    uses_shared_args: true,
                });
            }
            Mode::Direct => {
                if is_parallel {
                    if param_types.len() > 3 {
                        emit_array_wrapper(&mut out, handler, &fn_name, ret_type, true);
                        sigs.push(NativeSig {
                            fn_name: format!("{}_par_arr", fn_name),
                            param_types,
                            return_type: ret_type,
                            uses_shared_args: false,
                        });
                    } else {
                        sigs.push(NativeSig {
                            fn_name: format!("{}_par", fn_name),
                            param_types,
                            return_type: ret_type,
                            uses_shared_args: false,
                        });
                    }
                } else if param_types.len() > 3 {
                    emit_array_wrapper(&mut out, handler, &fn_name, ret_type, false);
                    sigs.push(NativeSig {
                        fn_name: format!("{}_arr", fn_name),
                        param_types,
                        return_type: ret_type,
                        uses_shared_args: false,
                    });
                } else {
                    sigs.push(NativeSig {
                        fn_name,
                        param_types,
                        return_type: ret_type,
                        uses_shared_args: false,
                    });
                }
            }
        }
    }

    (out, sigs)
}

// ── Mode selection ──────────────────────────────────────────────────

/// Decide whether a handler should use Direct or Rug mode.
///
/// Rule: a handler uses Rug mode if its return type is String. The user
/// opts into BigInt arithmetic by returning a String (the canonical
/// "BigInt-as-decimal-string" output). Everything else uses Direct mode
/// (Int=i64, Float=f64).
fn select_mode(handler: &NativeHandler, siblings: &HashSet<String>) -> Mode {
    let mut gen = FnGenerator::new(&handler.params, siblings, Mode::Direct);
    for p in &handler.params {
        gen.var_types.insert(p.name.clone(), type_expr_to_native(&p.ty.node));
    }
    gen.infer_body_types(&handler.body);
    let ret = gen.infer_return_type(&handler.body);
    if ret == NativeType::String {
        Mode::Rug
    } else {
        Mode::Direct
    }
}

// ── Direct mode handler ─────────────────────────────────────────────

fn gen_direct_handler(
    out: &mut String,
    gen: &FnGenerator,
    handler: &NativeHandler,
    fn_name: &str,
    ret_type: NativeType,
) {
    let param_str: String = handler.params.iter()
        .map(|p| {
            let ty = type_expr_to_native(&p.ty.node);
            format!("{}: {}", p.name, ty.rust_str())
        })
        .collect::<Vec<_>>()
        .join(", ");

    out.push_str(&format!(
        "#[no_mangle]\npub extern \"C\" fn {}({}) -> {} {{\n",
        fn_name, param_str, ret_type.rust_str()
    ));

    for stmt in &handler.body {
        out.push_str(&gen.gen_stmt_direct(&stmt.node, 1));
    }

    let last_is_return = handler.body.last()
        .map(|s| matches!(s.node, Statement::Return { .. }))
        .unwrap_or(false);
    if !last_is_return {
        let default = match ret_type {
            NativeType::Float => "    0.0f64\n",
            NativeType::Bool => "    false\n",
            NativeType::String => "    String::new()\n",
            NativeType::Int => "    0i64\n",
        };
        out.push_str(default);
    }
    out.push_str("}\n\n");
}

// ── Rug mode handler ────────────────────────────────────────────────

fn gen_rug_handler(
    out: &mut String,
    gen: &FnGenerator,
    handler: &NativeHandler,
    fn_name: &str,
) {
    out.push_str(&format!("#[no_mangle]\npub extern \"C\" fn {}() -> i64 {{\n", fn_name));

    // Read params from shared buffer
    for (i, p) in handler.params.iter().enumerate() {
        let ty = type_expr_to_native(&p.ty.node);
        if ty == NativeType::Int {
            out.push_str(&format!("    let mut {} = unsafe {{ _SOMA_ARGS[{}].clone() }};\n", p.name, i));
        } else {
            out.push_str(&format!("    let {} = unsafe {{ _SOMA_ARGS[{}].to_i64().unwrap_or(0) as {} }};\n",
                p.name, i, ty.rust_str()));
        }
    }

    for stmt in &handler.body {
        out.push_str(&gen.gen_stmt_rug(&stmt.node, 1));
    }

    let last_is_return = handler.body.last()
        .map(|s| matches!(s.node, Statement::Return { .. }))
        .unwrap_or(false);
    if !last_is_return { out.push_str("    0i64\n"); }
    out.push_str("}\n\n");
}

// ── Wrappers for parallel + many-arg handlers ───────────────────────

fn emit_parallel_wrapper(
    out: &mut String,
    handler: &NativeHandler,
    fn_name: &str,
    ret_type: NativeType,
    parallel: &ParallelConfig,
) {
    let n_threads = parallel.threads;
    let threads_expr = if n_threads > 0 {
        format!("{}usize", n_threads)
    } else {
        "std::thread::available_parallelism().map(|n| n.get()).unwrap_or(1)".to_string()
    };

    let first_param = &handler.params[0].name;
    let other_args: Vec<String> = handler.params[1..].iter().map(|p| p.name.clone()).collect();
    let full_param_str: String = handler.params.iter()
        .map(|p| format!("{}: {}", p.name, type_expr_to_native(&p.ty.node).rust_str()))
        .collect::<Vec<_>>()
        .join(", ");
    let other_args_str = if other_args.is_empty() {
        String::new()
    } else {
        format!(", {}", other_args.join(", "))
    };

    out.push_str(&format!(
        "#[no_mangle]\npub extern \"C\" fn {fn_name}_par({full_param_str}) -> {} {{\n\
        \tlet _n_threads = {threads_expr};\n\
        \tlet _total = {first_param} as usize;\n\
        \tif _total < _n_threads * 1000 {{\n\
        \t\treturn {fn_name}({first_param}{other_args_str});\n\
        \t}}\n\
        \tlet _chunk = (_total + _n_threads - 1) / _n_threads;\n\
        \tlet _result: f64 = std::thread::scope(|_s| {{\n\
        \t\tlet _handles: Vec<_> = (0.._n_threads).map(|_t| {{\n\
        \t\t\tlet _start = _t * _chunk;\n\
        \t\t\tlet _end = std::cmp::min((_t + 1) * _chunk, _total);\n\
        \t\t\tlet _chunk_n = (_end - _start) as i64;\n\
        \t\t\t_s.spawn(move || {{\n\
        \t\t\t\t{fn_name}(_chunk_n{other_args_str}) * _chunk_n as f64\n\
        \t\t\t}})\n\
        \t\t}}).collect();\n\
        \t\t_handles.into_iter().map(|h| h.join().unwrap()).sum::<f64>()\n\
        \t}});\n\
        \t(_result / {first_param} as f64) as {}\n\
        }}\n\n",
        ret_type.rust_str(), ret_type.rust_str()
    ));
}

fn emit_array_wrapper(
    out: &mut String,
    handler: &NativeHandler,
    fn_name: &str,
    ret_type: NativeType,
    is_parallel: bool,
) {
    let suffix = if is_parallel { "_par_arr" } else { "_arr" };
    let inner = if is_parallel { format!("{}_par", fn_name) } else { fn_name.to_string() };
    out.push_str(&format!("#[no_mangle]\npub extern \"C\" fn {}{}(args: *const f64, _count: i64) -> f64 {{\n", fn_name, suffix));
    out.push_str("    unsafe {\n");
    let call_args: Vec<String> = handler.params.iter().enumerate().map(|(i, p)| {
        let ty = type_expr_to_native(&p.ty.node);
        match ty {
            NativeType::Int => format!("*args.add({}) as i64", i),
            NativeType::Float => format!("*args.add({})", i),
            NativeType::Bool => format!("*args.add({}) != 0.0", i),
            NativeType::String => format!("*args.add({})", i),
        }
    }).collect();
    out.push_str(&format!("        let r = {}({});\n", inner, call_args.join(", ")));
    match ret_type {
        NativeType::Float => out.push_str("        r\n"),
        NativeType::Int => out.push_str("        r as f64\n"),
        NativeType::Bool => out.push_str("        if r { 1.0 } else { 0.0 }\n"),
        NativeType::String => out.push_str("        0.0\n"),
    }
    out.push_str("    }\n}\n\n");
}

// ── Type inference helpers ──────────────────────────────────────────

fn type_expr_to_native(ty: &TypeExpr) -> NativeType {
    match ty {
        TypeExpr::Simple(name) => match name.as_str() {
            "Int" => NativeType::Int,
            "Float" => NativeType::Float,
            "Bool" => NativeType::Bool,
            "String" => NativeType::String,
            _ => NativeType::Float,
        },
        _ => NativeType::Float,
    }
}

// ── FnGenerator ─────────────────────────────────────────────────────

struct FnGenerator {
    var_types: HashMap<String, NativeType>,
    siblings: HashSet<String>,
    mode: Mode,
    /// In Rug mode, Int variables that can be safely represented as i64
    /// (assigned only from literals or `self ± literal` patterns).
    small_int_vars: HashSet<String>,
}

impl FnGenerator {
    fn new(params: &[Param], siblings: &HashSet<String>, mode: Mode) -> Self {
        let mut var_types = HashMap::new();
        for p in params {
            var_types.insert(p.name.clone(), type_expr_to_native(&p.ty.node));
        }
        Self { var_types, siblings: siblings.clone(), mode, small_int_vars: HashSet::new() }
    }

    /// Classify Int variables: small (i64-safe) vs big (need rug::Integer).
    /// Only relevant in Rug mode.
    ///
    /// Fixpoint analysis: start with all Int locals in `small`. Repeatedly
    /// exclude any variable whose assignments use non-small variables or
    /// `var * var` (which can grow unboundedly). Iterate to fixpoint.
    ///
    /// Allowed expressions for a "small" variable:
    ///   - integer literal
    ///   - reference to another small variable (or self)
    ///   - small ± small, small / small, small % small
    ///   - small * literal, literal * small
    ///   - NOT small * small (potential unbounded growth)
    fn classify_int_vars(&mut self, body: &[Spanned<Statement>], int_params: &HashSet<String>) {
        if self.mode != Mode::Rug { return; }

        let mut small: HashSet<String> = self.var_types.iter()
            .filter(|(_, t)| **t == NativeType::Int)
            .map(|(n, _)| n.clone())
            .collect();
        // Int parameters arrive via shared buffer and may be BigInt at call site
        for p in int_params { small.remove(p); }

        // Iterate to fixpoint
        loop {
            let prev = small.clone();
            Self::exclude_non_small(body, &mut small);
            if small == prev { break; }
        }

        self.small_int_vars = small;
    }

    fn exclude_non_small(body: &[Spanned<Statement>], small: &mut HashSet<String>) {
        let mut to_remove: Vec<String> = Vec::new();
        Self::collect_non_small(body, small, &mut to_remove);
        for name in to_remove {
            small.remove(&name);
        }
    }

    fn collect_non_small(
        body: &[Spanned<Statement>],
        small: &HashSet<String>,
        to_remove: &mut Vec<String>,
    ) {
        for stmt in body {
            match &stmt.node {
                Statement::Let { name, value } | Statement::Assign { name, value } => {
                    if !small.contains(name) { continue; }
                    if !Self::is_small_expr(name, &value.node, small) {
                        to_remove.push(name.clone());
                    }
                }
                Statement::If { then_body, else_body, .. } => {
                    Self::collect_non_small(then_body, small, to_remove);
                    Self::collect_non_small(else_body, small, to_remove);
                }
                Statement::While { body, .. } => {
                    Self::collect_non_small(body, small, to_remove);
                }
                Statement::For { body, .. } => {
                    Self::collect_non_small(body, small, to_remove);
                }
                _ => {}
            }
        }
    }

    fn is_small_expr(target: &str, expr: &Expr, small: &HashSet<String>) -> bool {
        match expr {
            Expr::Literal(Literal::Int(_)) => true,
            Expr::Ident(n) => n == target || small.contains(n),
            Expr::BinaryOp { left, op, right } => {
                let l_ok = Self::is_small_expr(target, &left.node, small);
                let r_ok = Self::is_small_expr(target, &right.node, small);
                if !l_ok || !r_ok { return false; }
                // Disallow var * var (could grow unboundedly).
                // Allow lit*var, var*lit, lit*lit, and all +/-///%.
                if matches!(op, BinOp::Mul) {
                    let l_lit = matches!(&left.node, Expr::Literal(Literal::Int(_)));
                    let r_lit = matches!(&right.node, Expr::Literal(Literal::Int(_)));
                    if !l_lit && !r_lit { return false; }
                }
                matches!(op, BinOp::Add | BinOp::Sub | BinOp::Mul | BinOp::Div | BinOp::Mod)
            }
            _ => false,
        }
    }

    fn infer_body_types(&mut self, body: &[Spanned<Statement>]) {
        for stmt in body {
            self.infer_stmt_types(&stmt.node);
        }
    }

    fn infer_stmt_types(&mut self, stmt: &Statement) {
        match stmt {
            Statement::Let { name, value } => {
                let ty = self.infer_expr_type(&value.node);
                self.var_types.insert(name.clone(), ty);
            }
            Statement::Assign { name, value } => {
                let ty = self.infer_expr_type(&value.node);
                if let Some(existing) = self.var_types.get(name) {
                    if *existing == NativeType::Int && ty == NativeType::Float {
                        self.var_types.insert(name.clone(), NativeType::Float);
                    }
                } else {
                    self.var_types.insert(name.clone(), ty);
                }
            }
            Statement::If { then_body, else_body, .. } => {
                for s in then_body { self.infer_stmt_types(&s.node); }
                for s in else_body { self.infer_stmt_types(&s.node); }
            }
            Statement::While { body, .. } => {
                for s in body { self.infer_stmt_types(&s.node); }
            }
            Statement::For { var, iter, body, .. } => {
                self.var_types.insert(var.clone(), NativeType::Int);
                let _ = self.infer_expr_type(&iter.node);
                for s in body { self.infer_stmt_types(&s.node); }
            }
            _ => {}
        }
    }

    fn infer_expr_type(&self, expr: &Expr) -> NativeType {
        match expr {
            Expr::Literal(Literal::Int(_)) => NativeType::Int,
            Expr::Literal(Literal::Float(_)) => NativeType::Float,
            Expr::Literal(Literal::Bool(_)) => NativeType::Bool,
            Expr::Literal(Literal::String(_)) => NativeType::String,
            Expr::Ident(name) => self.var_types.get(name).copied().unwrap_or(NativeType::Float),
            Expr::BinaryOp { left, op, right } => {
                let lt = self.infer_expr_type(&left.node);
                let rt = self.infer_expr_type(&right.node);
                match op {
                    BinOp::Div => {
                        if lt == NativeType::Int && rt == NativeType::Int {
                            NativeType::Int
                        } else {
                            NativeType::Float
                        }
                    }
                    BinOp::And | BinOp::Or => NativeType::Bool,
                    BinOp::Add if lt == NativeType::String || rt == NativeType::String => NativeType::String,
                    _ => {
                        if lt == NativeType::Float || rt == NativeType::Float {
                            NativeType::Float
                        } else {
                            lt
                        }
                    }
                }
            }
            Expr::CmpOp { .. } => NativeType::Bool,
            Expr::Not(_) => NativeType::Bool,
            Expr::FnCall { name, args } => {
                match name.as_str() {
                    "random" | "sqrt" | "log" | "exp" | "pow" | "sin" | "cos" => NativeType::Float,
                    "to_string" => NativeType::String,
                    "to_float" => NativeType::Float,
                    "to_int" | "len" | "floor" | "ceil" | "round" => NativeType::Int,
                    "abs" | "min" | "max" => {
                        if args.is_empty() { NativeType::Float }
                        else { self.infer_expr_type(&args[0].node) }
                    }
                    other => {
                        // Recursive native handler call: assume Float unless we can do better.
                        // (We don't have access to sibling return types here.)
                        if self.siblings.contains(other) {
                            NativeType::Float
                        } else {
                            NativeType::Float
                        }
                    }
                }
            }
            _ => NativeType::Float,
        }
    }

    fn infer_return_type(&self, body: &[Spanned<Statement>]) -> NativeType {
        for stmt in body {
            match &stmt.node {
                Statement::Return { value } => {
                    return self.infer_expr_type(&value.node);
                }
                Statement::If { then_body, else_body, .. } => {
                    if let Some(ty) = self.find_return_type(then_body) { return ty; }
                    if let Some(ty) = self.find_return_type(else_body) { return ty; }
                }
                Statement::While { body, .. } => {
                    if let Some(ty) = self.find_return_type(body) { return ty; }
                }
                _ => {}
            }
        }
        if let Some(last) = body.last() {
            if let Statement::ExprStmt { expr } = &last.node {
                return self.infer_expr_type(&expr.node);
            }
        }
        NativeType::Float
    }

    fn find_return_type(&self, body: &[Spanned<Statement>]) -> Option<NativeType> {
        for stmt in body {
            match &stmt.node {
                Statement::Return { value } => return Some(self.infer_expr_type(&value.node)),
                Statement::If { then_body, else_body, .. } => {
                    if let Some(t) = self.find_return_type(then_body) { return Some(t); }
                    if let Some(t) = self.find_return_type(else_body) { return Some(t); }
                }
                Statement::While { body, .. } => {
                    if let Some(t) = self.find_return_type(body) { return Some(t); }
                }
                _ => {}
            }
        }
        None
    }

    fn indent(level: usize) -> String {
        "    ".repeat(level)
    }

    // ═══════════════════════════════════════════════════════════════
    // Direct mode codegen (Int=i64, Float=f64, Bool=bool)
    // ═══════════════════════════════════════════════════════════════

    fn gen_stmt_direct(&self, stmt: &Statement, indent: usize) -> String {
        let ind = Self::indent(indent);
        match stmt {
            Statement::Let { name, value } => {
                let ty = self.var_types.get(name).copied().unwrap_or(NativeType::Float);
                let expr = self.gen_expr_direct(&value.node, ty);
                format!("{}let mut {}: {} = {};\n", ind, name, ty.rust_str(), expr)
            }
            Statement::Assign { name, value } => {
                let ty = self.var_types.get(name).copied().unwrap_or(NativeType::Float);
                let expr = self.gen_expr_direct(&value.node, ty);
                format!("{}{} = {};\n", ind, name, expr)
            }
            Statement::Return { value } => {
                let ret_ty = self.infer_expr_type(&value.node);
                let expr = self.gen_expr_direct(&value.node, ret_ty);
                format!("{}return {};\n", ind, expr)
            }
            Statement::If { condition, then_body, else_body } => {
                let cond = self.gen_expr_direct(&condition.node, NativeType::Bool);
                let mut s = format!("{}if {} {{\n", ind, cond);
                for st in then_body {
                    s.push_str(&self.gen_stmt_direct(&st.node, indent + 1));
                }
                if else_body.is_empty() {
                    s.push_str(&format!("{}}}\n", ind));
                } else {
                    s.push_str(&format!("{}}} else {{\n", ind));
                    for st in else_body {
                        s.push_str(&self.gen_stmt_direct(&st.node, indent + 1));
                    }
                    s.push_str(&format!("{}}}\n", ind));
                }
                s
            }
            Statement::While { condition, body } => {
                let cond = self.gen_expr_direct(&condition.node, NativeType::Bool);
                let mut s = format!("{}while {} {{\n", ind, cond);
                for st in body {
                    s.push_str(&self.gen_stmt_direct(&st.node, indent + 1));
                }
                s.push_str(&format!("{}}}\n", ind));
                s
            }
            Statement::For { var, iter, body } => {
                let iter_code = self.gen_for_iter_direct(&iter.node);
                let mut s = format!("{}for {} in {} {{\n", ind, var, iter_code);
                for st in body {
                    s.push_str(&self.gen_stmt_direct(&st.node, indent + 1));
                }
                s.push_str(&format!("{}}}\n", ind));
                s
            }
            Statement::Break => format!("{}break;\n", ind),
            Statement::Continue => format!("{}continue;\n", ind),
            Statement::ExprStmt { expr } => {
                let code = self.gen_expr_direct(&expr.node, NativeType::Float);
                format!("{}let _ = {};\n", ind, code)
            }
            _ => format!("{}// unsupported statement\n", ind),
        }
    }

    fn gen_for_iter_direct(&self, expr: &Expr) -> String {
        if let Expr::FnCall { name, args } = expr {
            if name == "range" && args.len() == 2 {
                let a = self.gen_expr_direct(&args[0].node, NativeType::Int);
                let b = self.gen_expr_direct(&args[1].node, NativeType::Int);
                return format!("{}..{}", a, b);
            }
        }
        format!("0..0 /* unsupported iterator */")
    }

    fn gen_expr_direct(&self, expr: &Expr, target_ty: NativeType) -> String {
        match expr {
            Expr::Literal(Literal::Int(n)) => {
                match target_ty {
                    NativeType::Float => format!("{}.0f64", n),
                    _ => format!("{}i64", n),
                }
            }
            Expr::Literal(Literal::Float(f)) => format!("{}f64", f),
            Expr::Literal(Literal::Bool(b)) => format!("{}", b),
            Expr::Literal(Literal::String(s)) => {
                format!("\"{}\".to_string()", s.replace('\\', "\\\\").replace('"', "\\\""))
            }
            Expr::Ident(name) => {
                let var_ty = self.var_types.get(name).copied().unwrap_or(NativeType::Float);
                self.coerce_direct(name.clone(), var_ty, target_ty)
            }
            Expr::BinaryOp { left, op, right } => {
                self.gen_binop_direct(&left.node, *op, &right.node, target_ty)
            }
            Expr::CmpOp { left, op, right } => {
                let lt = self.infer_expr_type(&left.node);
                let rt = self.infer_expr_type(&right.node);
                let common = if lt == NativeType::Float || rt == NativeType::Float {
                    NativeType::Float
                } else if lt == NativeType::String || rt == NativeType::String {
                    NativeType::String
                } else {
                    NativeType::Int
                };
                let l = self.gen_expr_direct(&left.node, common);
                let r = self.gen_expr_direct(&right.node, common);
                let op_str = match op {
                    CmpOp::Lt => "<", CmpOp::Gt => ">", CmpOp::Le => "<=",
                    CmpOp::Ge => ">=", CmpOp::Eq => "==", CmpOp::Ne => "!=",
                };
                format!("({} {} {})", l, op_str, r)
            }
            Expr::Not(inner) => {
                let e = self.gen_expr_direct(&inner.node, NativeType::Bool);
                format!("(!{})", e)
            }
            Expr::FnCall { name, args } => self.gen_fn_call_direct(name, args, target_ty),
            _ => "0i64 /* unsupported direct expr */".to_string(),
        }
    }

    /// Coerce a value of `from` type to `to` type in Direct mode.
    fn coerce_direct(&self, expr: String, from: NativeType, to: NativeType) -> String {
        if from == to { return expr; }
        match (from, to) {
            (NativeType::Int, NativeType::Float) => format!("({} as f64)", expr),
            (NativeType::Float, NativeType::Int) => format!("({} as i64)", expr),
            (NativeType::Bool, NativeType::Int) => format!("({} as i64)", expr),
            (NativeType::Int, NativeType::Bool) => format!("({} != 0)", expr),
            (_, NativeType::String) => format!("format!(\"{{}}\", {})", expr),
            _ => expr,
        }
    }

    fn gen_binop_direct(&self, left: &Expr, op: BinOp, right: &Expr, target_ty: NativeType) -> String {
        let lt = self.infer_expr_type(left);
        let rt = self.infer_expr_type(right);

        // Logical
        if matches!(op, BinOp::And | BinOp::Or) {
            let l = self.gen_expr_direct(left, NativeType::Bool);
            let r = self.gen_expr_direct(right, NativeType::Bool);
            let op_str = if matches!(op, BinOp::And) { "&&" } else { "||" };
            return format!("({} {} {})", l, op_str, r);
        }

        // String concat
        if matches!(op, BinOp::Add) && (lt == NativeType::String || rt == NativeType::String) {
            let l = self.gen_expr_direct(left, NativeType::String);
            let r = self.gen_expr_direct(right, NativeType::String);
            return format!("format!(\"{{}}{{}}\", {}, {})", l, r);
        }

        // Numeric: pick common type (Float dominates)
        let common = if lt == NativeType::Float || rt == NativeType::Float {
            NativeType::Float
        } else {
            NativeType::Int
        };
        let l = self.gen_expr_direct(left, common);
        let r = self.gen_expr_direct(right, common);
        let op_str = match op {
            BinOp::Add => "+", BinOp::Sub => "-", BinOp::Mul => "*",
            BinOp::Div => "/", BinOp::Mod => "%", _ => "+",
        };
        let inner = format!("({} {} {})", l, op_str, r);
        // Coerce to target if needed
        self.coerce_direct(inner, common, target_ty)
    }

    fn gen_fn_call_direct(&self, name: &str, args: &[Spanned<Expr>], target_ty: NativeType) -> String {
        match name {
            "random" => "unsafe { _soma_random() }".to_string(),
            "sqrt" | "log" | "exp" | "sin" | "cos" => {
                let a = self.gen_expr_direct(&args[0].node, NativeType::Float);
                let method = match name { "log" => "ln", other => other };
                format!("({}).{}()", a, method)
            }
            "pow" => {
                let a = self.gen_expr_direct(&args[0].node, NativeType::Float);
                let b = self.gen_expr_direct(&args[1].node, NativeType::Float);
                format!("({}).powf({})", a, b)
            }
            "abs" => {
                let a_ty = self.infer_expr_type(&args[0].node);
                let a = self.gen_expr_direct(&args[0].node, a_ty);
                format!("({}).abs()", a)
            }
            "min" | "max" if args.len() == 2 => {
                let a_ty = self.infer_expr_type(&args[0].node);
                let b_ty = self.infer_expr_type(&args[1].node);
                let common = if a_ty == NativeType::Float || b_ty == NativeType::Float {
                    NativeType::Float
                } else {
                    NativeType::Int
                };
                let a = self.gen_expr_direct(&args[0].node, common);
                let b = self.gen_expr_direct(&args[1].node, common);
                if common == NativeType::Float {
                    format!("({}).{}({})", a, name, b)
                } else {
                    format!("std::cmp::{}({}, {})", name, a, b)
                }
            }
            "floor" | "ceil" | "round" => {
                let a = self.gen_expr_direct(&args[0].node, NativeType::Float);
                format!("(({}).{}() as i64)", a, name)
            }
            "to_int" => {
                let a_ty = self.infer_expr_type(&args[0].node);
                let a = self.gen_expr_direct(&args[0].node, a_ty);
                format!("({} as i64)", a)
            }
            "to_float" => {
                let a_ty = self.infer_expr_type(&args[0].node);
                let a = self.gen_expr_direct(&args[0].node, a_ty);
                format!("({} as f64)", a)
            }
            "to_string" => {
                let a_ty = self.infer_expr_type(&args[0].node);
                let a = self.gen_expr_direct(&args[0].node, a_ty);
                format!("format!(\"{{}}\", {})", a)
            }
            "len" => {
                let arg_ty = self.infer_expr_type(&args[0].node);
                if arg_ty == NativeType::String {
                    let a = self.gen_expr_direct(&args[0].node, NativeType::String);
                    format!("({}.len() as i64)", a)
                } else {
                    "0i64 /* len: unsupported */".to_string()
                }
            }
            "range" if args.len() == 2 => {
                let a = self.gen_expr_direct(&args[0].node, NativeType::Int);
                let b = self.gen_expr_direct(&args[1].node, NativeType::Int);
                format!("({}..{})", a, b)
            }
            other => {
                // Sibling native handler call
                let arg_strs: Vec<String> = args.iter()
                    .map(|a| {
                        let ty = self.infer_expr_type(&a.node);
                        self.gen_expr_direct(&a.node, ty)
                    })
                    .collect();
                let call = format!("handler_{}({})", other, arg_strs.join(", "));
                // Sibling handlers we can't easily type-infer; assume Float by default
                self.coerce_direct(call, NativeType::Float, target_ty)
            }
        }
    }

    // ═══════════════════════════════════════════════════════════════
    // Rug mode codegen (Int=rug::Integer, Float=f64)
    // ═══════════════════════════════════════════════════════════════

    fn gen_stmt_rug(&self, stmt: &Statement, indent: usize) -> String {
        let ind = Self::indent(indent);
        match stmt {
            Statement::Let { name, value } => {
                let ty = self.var_types.get(name).copied().unwrap_or(NativeType::Float);
                match ty {
                    NativeType::Int if self.small_int_vars.contains(name) => {
                        // Small counter — represent as i64
                        let expr = self.gen_expr_direct(&value.node, NativeType::Int);
                        format!("{}let mut {}: i64 = {};\n", ind, name, expr)
                    }
                    NativeType::Int => {
                        let expr = self.gen_expr_rug(&value.node);
                        format!("{}let mut {}: Integer = {};\n", ind, name, expr)
                    }
                    NativeType::String => {
                        let expr = self.gen_expr_rug_string(&value.node);
                        format!("{}let mut {}: String = {};\n", ind, name, expr)
                    }
                    NativeType::Float => {
                        let expr = self.gen_expr_direct(&value.node, NativeType::Float);
                        format!("{}let mut {}: f64 = {};\n", ind, name, expr)
                    }
                    NativeType::Bool => {
                        let expr = self.gen_expr_direct(&value.node, NativeType::Bool);
                        format!("{}let mut {}: bool = {};\n", ind, name, expr)
                    }
                }
            }
            Statement::Assign { name, value } => {
                let ty = self.var_types.get(name).copied().unwrap_or(NativeType::Float);
                match ty {
                    NativeType::Int if self.small_int_vars.contains(name) => {
                        // Small counter — i64 assignment
                        let expr = self.gen_expr_direct(&value.node, NativeType::Int);
                        format!("{}{} = {};\n", ind, name, expr)
                    }
                    NativeType::Int => self.gen_assign_rug(name, &value.node, &ind),
                    NativeType::String => {
                        // Optimize: name = name + to_string(int_var) → write!(name, "{}", int_var)
                        // This avoids the intermediate String allocation per iteration.
                        if let Expr::BinaryOp { left, op: BinOp::Add, right } = &value.node {
                            if let Expr::Ident(ref lname) = left.node {
                                if lname == name {
                                    // Check for to_string(ident_int)
                                    if let Expr::FnCall { name: fname, args } = &right.node {
                                        if fname == "to_string" && args.len() == 1 {
                                            let arg_ty = self.infer_expr_type(&args[0].node);
                                            if arg_ty == NativeType::Int {
                                                if let Expr::Ident(ref vname) = args[0].node {
                                                    return format!(
                                                        "{}{{ use std::fmt::Write; write!({}, \"{{}}\", {}).unwrap(); }}\n",
                                                        ind, name, vname
                                                    );
                                                }
                                            }
                                        }
                                    }
                                    let rhs = self.gen_expr_rug_string(&right.node);
                                    return format!("{}{}.push_str(&{});\n", ind, name, rhs);
                                }
                            }
                        }
                        let expr = self.gen_expr_rug_string(&value.node);
                        format!("{}{} = {};\n", ind, name, expr)
                    }
                    _ => {
                        let expr = self.gen_expr_direct(&value.node, ty);
                        format!("{}{} = {};\n", ind, name, expr)
                    }
                }
            }
            Statement::Return { value } => {
                let ret_ty = self.infer_expr_type(&value.node);
                if ret_ty == NativeType::Int {
                    let expr = self.gen_expr_rug(&value.node);
                    let mut s = String::new();
                    s.push_str(&format!("{}{{\n", ind));
                    s.push_str(&format!("{}    let _ret_val: Integer = {};\n", ind, expr));
                    s.push_str(&format!("{}    if let Some(v) = _ret_val.to_i64() {{\n", ind));
                    s.push_str(&format!("{}        return v;\n", ind));
                    s.push_str(&format!("{}    }} else {{\n", ind));
                    s.push_str(&format!("{}        unsafe {{ _SOMA_RESULT = Some(_ret_val.to_string()); }}\n", ind));
                    s.push_str(&format!("{}        return i64::MIN;\n", ind));
                    s.push_str(&format!("{}    }}\n", ind));
                    s.push_str(&format!("{}}}\n", ind));
                    s
                } else if ret_ty == NativeType::String {
                    let expr = self.gen_expr_rug_string(&value.node);
                    let mut s = String::new();
                    s.push_str(&format!("{}unsafe {{ _SOMA_RESULT = Some({}); }}\n", ind, expr));
                    s.push_str(&format!("{}return i64::MIN + 1;\n", ind));
                    s
                } else {
                    let expr = self.gen_expr_direct(&value.node, ret_ty);
                    format!("{}return {};\n", ind, expr)
                }
            }
            Statement::If { condition, then_body, else_body } => {
                let cond = self.gen_cond_rug(&condition.node);
                let mut s = format!("{}if {} {{\n", ind, cond);
                for st in then_body { s.push_str(&self.gen_stmt_rug(&st.node, indent + 1)); }
                if else_body.is_empty() {
                    s.push_str(&format!("{}}}\n", ind));
                } else {
                    s.push_str(&format!("{}}} else {{\n", ind));
                    for st in else_body { s.push_str(&self.gen_stmt_rug(&st.node, indent + 1)); }
                    s.push_str(&format!("{}}}\n", ind));
                }
                s
            }
            Statement::While { condition, body } => {
                let cond = self.gen_cond_rug(&condition.node);
                let mut s = String::new();

                // Hoist loop-internal Integer variables before the loop
                let mut hoisted: HashSet<String> = HashSet::new();
                self.collect_loop_int_vars(body, &mut hoisted);
                for var in &hoisted {
                    s.push_str(&format!("{}let mut {}: Integer = Integer::new();\n", ind, var));
                }

                s.push_str(&format!("{}while {} {{\n", ind, cond));
                for st in body {
                    s.push_str(&self.gen_stmt_rug_hoisted(&st.node, indent + 1, &hoisted));
                }
                s.push_str(&format!("{}}}\n", ind));
                s
            }
            Statement::For { var, iter, body } => {
                let iter_code = self.gen_for_iter_direct(&iter.node);
                let mut s = format!("{}for {} in {} {{\n", ind, var, iter_code);
                for st in body { s.push_str(&self.gen_stmt_rug(&st.node, indent + 1)); }
                s.push_str(&format!("{}}}\n", ind));
                s
            }
            Statement::Break => format!("{}break;\n", ind),
            Statement::Continue => format!("{}continue;\n", ind),
            Statement::ExprStmt { expr } => {
                let code = self.gen_expr_rug(&expr.node);
                format!("{}let _ = {};\n", ind, code)
            }
            _ => format!("{}// unsupported statement\n", ind),
        }
    }

    fn collect_loop_int_vars(&self, body: &[Spanned<Statement>], vars: &mut HashSet<String>) {
        for stmt in body {
            match &stmt.node {
                Statement::Let { name, .. } => {
                    let ty = self.var_types.get(name).copied().unwrap_or(NativeType::Float);
                    // Don't hoist small Int vars — they're plain i64, not Integer
                    if ty == NativeType::Int && !self.small_int_vars.contains(name) {
                        vars.insert(name.clone());
                    }
                }
                Statement::If { then_body, else_body, .. } => {
                    self.collect_loop_int_vars(then_body, vars);
                    self.collect_loop_int_vars(else_body, vars);
                }
                _ => {}
            }
        }
    }

    fn gen_stmt_rug_hoisted(&self, stmt: &Statement, indent: usize, hoisted: &HashSet<String>) -> String {
        match stmt {
            Statement::Let { name, value } => {
                let ty = self.var_types.get(name).copied().unwrap_or(NativeType::Float);
                if ty == NativeType::Int
                    && !self.small_int_vars.contains(name)
                    && hoisted.contains(name)
                {
                    let ind = Self::indent(indent);
                    return self.gen_assign_rug(name, &value.node, &ind);
                }
                self.gen_stmt_rug(stmt, indent)
            }
            Statement::If { condition, then_body, else_body } => {
                let ind = Self::indent(indent);
                let cond = self.gen_cond_rug(&condition.node);
                let mut s = format!("{}if {} {{\n", ind, cond);
                for st in then_body {
                    s.push_str(&self.gen_stmt_rug_hoisted(&st.node, indent + 1, hoisted));
                }
                if else_body.is_empty() {
                    s.push_str(&format!("{}}}\n", ind));
                } else {
                    s.push_str(&format!("{}}} else {{\n", ind));
                    for st in else_body {
                        s.push_str(&self.gen_stmt_rug_hoisted(&st.node, indent + 1, hoisted));
                    }
                    s.push_str(&format!("{}}}\n", ind));
                }
                s
            }
            _ => self.gen_stmt_rug(stmt, indent),
        }
    }

    /// Rug-mode expression returning rug::Integer.
    fn gen_expr_rug(&self, expr: &Expr) -> String {
        match expr {
            Expr::Literal(Literal::Int(n)) => format!("Integer::from({}i64)", n),
            Expr::Ident(name) => {
                let var_ty = self.var_types.get(name).copied().unwrap_or(NativeType::Float);
                if var_ty == NativeType::Int {
                    if self.small_int_vars.contains(name) {
                        format!("Integer::from({})", name)
                    } else {
                        format!("{}.clone()", name)
                    }
                } else if var_ty == NativeType::Float {
                    format!("Integer::from({} as i64)", name)
                } else {
                    name.clone()
                }
            }
            Expr::BinaryOp { left, op, right } => {
                let lt = self.infer_expr_type(&left.node);
                let rt = self.infer_expr_type(&right.node);
                if lt == NativeType::Int && rt == NativeType::Int {
                    self.gen_binop_rug(&left.node, *op, &right.node)
                } else {
                    format!("Integer::from(0i64) /* mixed binop in rug expr */")
                }
            }
            Expr::FnCall { name, args } => self.gen_fn_call_rug(name, args),
            _ => "Integer::from(0i64) /* unsupported rug expr */".to_string()
        }
    }

    /// Rug-mode binop returning rug::Integer.
    fn gen_binop_rug(&self, left: &Expr, op: BinOp, right: &Expr) -> String {
        let op_str = match op {
            BinOp::Add => "+", BinOp::Sub => "-", BinOp::Mul => "*",
            BinOp::Div => "/", BinOp::Mod => "%", _ => "+",
        };
        // If both operands are small (i64), do pure i64 arithmetic
        if self.is_small_int_expr(left) && self.is_small_int_expr(right) {
            let l = self.gen_expr_direct(left, NativeType::Int);
            let r = self.gen_expr_direct(right, NativeType::Int);
            return format!("Integer::from({} {} {})", l, op_str, r);
        }
        // Mixed: pick representation that rug supports
        // Rug supports: Integer op &Integer, Integer op u32/i32/u64/i64
        // For "small * Integer" we want: small as i64 * &big = Integer
        let l = self.gen_expr_rug_operand(left, right);
        let r = self.gen_expr_rug_operand(right, left);
        format!("Integer::from({} {} {})", l, op_str, r)
    }

    /// Generate an operand for a binop, choosing representation based on
    /// what the OTHER operand looks like. Used to avoid u32 * i64 mismatches.
    fn gen_expr_rug_operand(&self, expr: &Expr, _other: &Expr) -> String {
        match expr {
            Expr::Literal(Literal::Int(n)) => {
                // Default to i64 (rug supports Integer op i64) so it works
                // with both Integer and i64 other-side
                format!("{}i64", n)
            }
            Expr::Ident(name) => {
                let var_ty = self.var_types.get(name).copied().unwrap_or(NativeType::Float);
                if var_ty == NativeType::Int {
                    if self.small_int_vars.contains(name) {
                        name.clone()  // i64
                    } else {
                        format!("&{}", name)  // &Integer
                    }
                } else {
                    format!("{} as i64", name)
                }
            }
            Expr::BinaryOp { left, op, right } => {
                let inner = self.gen_binop_rug(&left.node, *op, &right.node);
                format!("&{}", inner)
            }
            Expr::FnCall { name, args } => {
                let inner = self.gen_fn_call_rug(name, args);
                format!("&{}", inner)
            }
            _ => format!("&{}", self.gen_expr_rug(expr)),
        }
    }

    /// Generate an "incomplete" rug expression suitable for x.assign(...).
    fn gen_expr_rug_incomplete(&self, expr: &Expr) -> String {
        match expr {
            Expr::Literal(Literal::Int(n)) => format!("{}i64", n),
            Expr::BinaryOp { left, op, right } => {
                let lt = self.infer_expr_type(&left.node);
                let rt = self.infer_expr_type(&right.node);
                if lt == NativeType::Int && rt == NativeType::Int {
                    // Use the same operand-aware generation as gen_binop_rug
                    let op_str = match op {
                        BinOp::Add => "+", BinOp::Sub => "-", BinOp::Mul => "*",
                        BinOp::Div => "/", BinOp::Mod => "%", _ => "+",
                    };
                    if self.is_small_int_expr(&left.node) && self.is_small_int_expr(&right.node) {
                        // Both small → assign from i64
                        let l = self.gen_expr_direct(&left.node, NativeType::Int);
                        let r = self.gen_expr_direct(&right.node, NativeType::Int);
                        return format!("{} {} {}", l, op_str, r);
                    }
                    let l = self.gen_expr_rug_operand(&left.node, &right.node);
                    let r = self.gen_expr_rug_operand(&right.node, &left.node);
                    format!("{} {} {}", l, op_str, r)
                } else {
                    self.gen_expr_rug(expr)
                }
            }
            _ => self.gen_expr_rug(expr),
        }
    }

    /// Reference-form Integer expression for use as operand.
    /// For "big" Integer vars: emit &name. For "small" i64 vars: emit name (rug ops support i64).
    fn gen_expr_rug_ref(&self, expr: &Expr) -> String {
        match expr {
            Expr::Literal(Literal::Int(n)) => {
                if *n >= 0 && *n <= u32::MAX as i64 {
                    format!("{}u32", n)
                } else if *n >= i32::MIN as i64 && *n <= i32::MAX as i64 {
                    format!("{}i32", n)
                } else {
                    format!("&Integer::from({}i64)", n)
                }
            }
            Expr::Ident(name) => {
                let var_ty = self.var_types.get(name).copied().unwrap_or(NativeType::Float);
                if var_ty == NativeType::Int {
                    if self.small_int_vars.contains(name) {
                        // i64 variable — rug supports Integer op i64 directly
                        name.clone()
                    } else {
                        format!("&{}", name)
                    }
                } else {
                    format!("{} as i32", name)
                }
            }
            Expr::BinaryOp { left, op, right } => {
                let inner = self.gen_binop_rug(&left.node, *op, &right.node);
                format!("&{}", inner)
            }
            Expr::FnCall { name, args } => {
                let inner = self.gen_fn_call_rug(name, args);
                format!("&{}", inner)
            }
            _ => format!("&{}", self.gen_expr_rug(expr)),
        }
    }

    /// Efficient in-place Integer assignment.
    fn gen_assign_rug(&self, name: &str, value: &Expr, ind: &str) -> String {
        // Pattern: name = name OP expr  →  name OP= expr
        if let Expr::BinaryOp { left, op, right } = value {
            if let Expr::Ident(ref lname) = left.node {
                if lname == name {
                    let op_assign = match op {
                        BinOp::Add => "+=", BinOp::Sub => "-=", BinOp::Mul => "*=",
                        BinOp::Div => "/=", BinOp::Mod => "%=", _ => "",
                    };
                    if !op_assign.is_empty() {
                        let r = self.gen_expr_rug_ref(&right.node);
                        return format!("{}{} {} {};\n", ind, name, op_assign, r);
                    }
                }
            }
            if let Expr::Ident(ref rname) = right.node {
                if rname == name && matches!(op, BinOp::Add | BinOp::Mul) {
                    let op_assign = match op {
                        BinOp::Add => "+=", BinOp::Mul => "*=", _ => "",
                    };
                    if !op_assign.is_empty() {
                        let l = self.gen_expr_rug_ref(&left.node);
                        return format!("{}{} {} {};\n", ind, name, op_assign, l);
                    }
                }
            }
        }

        // Literal assign: x.assign(N)
        if let Expr::Literal(Literal::Int(n)) = value {
            return format!("{}{}.assign({}i64);\n", ind, name, n);
        }

        // Simple ident → swap (O(1))
        if let Expr::Ident(ref src) = value {
            let var_ty = self.var_types.get(src).copied().unwrap_or(NativeType::Float);
            if var_ty == NativeType::Int && src != name {
                return format!("{}std::mem::swap(&mut {}, &mut {});\n", ind, name, src);
            }
        }

        // General: x.assign(incomplete_expr)
        let expr = self.gen_expr_rug_incomplete(value);
        format!("{}{}.assign({});\n", ind, name, expr)
    }

    /// Boolean condition for if/while in Rug mode.
    fn gen_cond_rug(&self, expr: &Expr) -> String {
        match expr {
            Expr::CmpOp { left, op, right } => {
                let lt = self.infer_expr_type(&left.node);
                let rt = self.infer_expr_type(&right.node);
                if lt == NativeType::Int && rt == NativeType::Int {
                    // Check if both operands are small (i64) → primitive comparison
                    let l_small = self.is_small_int_expr(&left.node);
                    let r_small = self.is_small_int_expr(&right.node);
                    let op_str = match op {
                        CmpOp::Lt => "<", CmpOp::Gt => ">", CmpOp::Le => "<=",
                        CmpOp::Ge => ">=", CmpOp::Eq => "==", CmpOp::Ne => "!=",
                    };
                    if l_small && r_small {
                        // Pure i64 comparison
                        let l = self.gen_expr_direct(&left.node, NativeType::Int);
                        let r = self.gen_expr_direct(&right.node, NativeType::Int);
                        return format!("({} {} {})", l, op_str, r);
                    }
                    // Mixed Integer/i64 or pure Integer
                    let l = self.gen_cmp_operand_rug(&left.node);
                    let r = self.gen_cmp_operand_rug(&right.node);
                    format!("{} {} {}", l, op_str, r)
                } else {
                    let common = if lt == NativeType::Float || rt == NativeType::Float {
                        NativeType::Float
                    } else {
                        NativeType::Int
                    };
                    let l = self.gen_expr_direct(&left.node, common);
                    let r = self.gen_expr_direct(&right.node, common);
                    let op_str = match op {
                        CmpOp::Lt => "<", CmpOp::Gt => ">", CmpOp::Le => "<=",
                        CmpOp::Ge => ">=", CmpOp::Eq => "==", CmpOp::Ne => "!=",
                    };
                    format!("({} {} {})", l, op_str, r)
                }
            }
            Expr::Not(inner) => {
                let e = self.gen_cond_rug(&inner.node);
                format!("(!{})", e)
            }
            Expr::BinaryOp { left, op, right } if matches!(op, BinOp::And | BinOp::Or) => {
                let l = self.gen_cond_rug(&left.node);
                let r = self.gen_cond_rug(&right.node);
                let op_str = if matches!(op, BinOp::And) { "&&" } else { "||" };
                format!("({} {} {})", l, op_str, r)
            }
            Expr::Literal(Literal::Bool(b)) => format!("{}", b),
            Expr::Ident(name) => name.clone(),
            _ => "true /* unsupported rug cond */".to_string()
        }
    }

    /// True if expr only references small_int_vars or i64 literals.
    fn is_small_int_expr(&self, expr: &Expr) -> bool {
        match expr {
            Expr::Literal(Literal::Int(_)) => true,
            Expr::Ident(name) => self.small_int_vars.contains(name),
            Expr::BinaryOp { left, right, .. } => {
                self.is_small_int_expr(&left.node) && self.is_small_int_expr(&right.node)
            }
            _ => false,
        }
    }

    fn gen_cmp_operand_rug(&self, expr: &Expr) -> String {
        match expr {
            Expr::Literal(Literal::Int(n)) => {
                // rug::Integer compares with i64 directly
                format!("{}i64", n)
            }
            Expr::Ident(name) => name.clone(),
            _ => self.gen_expr_rug(expr),
        }
    }

    /// Boolean condition: handle small/big mixing in comparisons.
    /// rug::Integer supports comparison with i64 directly.
    /// i64 vs i64 needs primitive comparison.

    /// String expression in Rug mode.
    fn gen_expr_rug_string(&self, expr: &Expr) -> String {
        match expr {
            Expr::Literal(Literal::String(s)) => {
                format!("\"{}\".to_string()", s.replace('\\', "\\\\").replace('"', "\\\""))
            }
            Expr::BinaryOp { left, op: BinOp::Add, right } => {
                let l = self.gen_expr_rug_string(&left.node);
                let r = self.gen_expr_rug_string(&right.node);
                format!("format!(\"{{}}{{}}\", {}, {})", l, r)
            }
            Expr::FnCall { name, args } if name == "to_string" && args.len() == 1 => {
                let arg_ty = self.infer_expr_type(&args[0].node);
                if arg_ty == NativeType::Int {
                    if let Expr::Ident(ref vname) = args[0].node {
                        format!("{}.to_string()", vname)
                    } else {
                        let a = self.gen_expr_rug(&args[0].node);
                        format!("{}.to_string()", a)
                    }
                } else {
                    let a = self.gen_expr_direct(&args[0].node, arg_ty);
                    format!("format!(\"{{}}\", {})", a)
                }
            }
            Expr::Ident(name) => {
                let var_ty = self.var_types.get(name).copied().unwrap_or(NativeType::Float);
                if var_ty == NativeType::String {
                    format!("{}.clone()", name)
                } else if var_ty == NativeType::Int {
                    format!("{}.to_string()", name)
                } else {
                    format!("format!(\"{{}}\", {})", name)
                }
            }
            _ => {
                let inner = self.gen_expr_rug(expr);
                format!("{}.to_string()", inner)
            }
        }
    }

    fn gen_fn_call_rug(&self, name: &str, args: &[Spanned<Expr>]) -> String {
        match name {
            "abs" => {
                let a = self.gen_expr_rug(&args[0].node);
                format!("({}).abs()", a)
            }
            "to_int" => {
                let a_ty = self.infer_expr_type(&args[0].node);
                if a_ty == NativeType::Int {
                    self.gen_expr_rug(&args[0].node)
                } else {
                    let a = self.gen_expr_direct(&args[0].node, a_ty);
                    format!("Integer::from({} as i64)", a)
                }
            }
            "floor" | "ceil" | "round" => {
                let a = self.gen_expr_direct(&args[0].node, NativeType::Float);
                format!("Integer::from(({}).{}() as i64)", a, name)
            }
            other => {
                if self.siblings.contains(other) {
                    let arg_strs: Vec<String> = args.iter()
                        .map(|a| {
                            let ty = self.infer_expr_type(&a.node);
                            self.gen_expr_direct(&a.node, ty)
                        })
                        .collect();
                    format!("Integer::from(handler_{}({}) as i64)", other, arg_strs.join(", "))
                } else {
                    format!("Integer::from(0i64) /* unknown fn: {} */", other)
                }
            }
        }
    }
}

// ── Shared buffer source for Rug mode ───────────────────────────────

const SHARED_BUFFER_RUG: &str = r#"
// Shared arg/result buffer for Rug-mode handlers
static mut _SOMA_ARGS: Vec<Integer> = Vec::new();
static mut _SOMA_RESULT: Option<String> = None;

#[no_mangle]
pub extern "C" fn _soma_clear_args() {
    unsafe { _SOMA_ARGS.clear(); }
}

#[no_mangle]
pub extern "C" fn _soma_push_i64(v: i64) {
    unsafe { _SOMA_ARGS.push(Integer::from(v)); }
}

#[no_mangle]
pub extern "C" fn _soma_push_bigint(ptr: *const u8, len: i64) {
    unsafe {
        let bytes = std::slice::from_raw_parts(ptr, len as usize);
        let s = std::str::from_utf8_unchecked(bytes);
        let val = Integer::parse(s).unwrap();
        _SOMA_ARGS.push(Integer::from(val));
    }
}

#[no_mangle]
pub extern "C" fn _soma_result_ptr() -> *const u8 {
    unsafe { _SOMA_RESULT.as_ref().map(|s| s.as_ptr()).unwrap_or(std::ptr::null()) }
}

#[no_mangle]
pub extern "C" fn _soma_result_len() -> i64 {
    unsafe { _SOMA_RESULT.as_ref().map(|s| s.len() as i64).unwrap_or(0) }
}
"#;

// ── random() detection ──────────────────────────────────────────────

fn body_uses_random(body: &[Spanned<Statement>]) -> bool {
    body.iter().any(|s| stmt_uses_random(&s.node))
}

fn stmt_uses_random(stmt: &Statement) -> bool {
    match stmt {
        Statement::Let { value, .. } | Statement::Assign { value, .. } | Statement::Return { value } => {
            expr_uses_random(&value.node)
        }
        Statement::If { condition, then_body, else_body } => {
            expr_uses_random(&condition.node) || body_uses_random(then_body) || body_uses_random(else_body)
        }
        Statement::While { condition, body } => {
            expr_uses_random(&condition.node) || body_uses_random(body)
        }
        Statement::For { iter, body, .. } => {
            expr_uses_random(&iter.node) || body_uses_random(body)
        }
        Statement::ExprStmt { expr } => expr_uses_random(&expr.node),
        _ => false,
    }
}

fn expr_uses_random(expr: &Expr) -> bool {
    match expr {
        Expr::FnCall { name, args } => {
            name == "random" || args.iter().any(|a| expr_uses_random(&a.node))
        }
        Expr::BinaryOp { left, right, .. } | Expr::CmpOp { left, right, .. } => {
            expr_uses_random(&left.node) || expr_uses_random(&right.node)
        }
        Expr::Not(inner) => expr_uses_random(&inner.node),
        _ => false,
    }
}
