//! `soma docs` — render generated reference documentation.
//! The compiler is the single source of truth: this command renders the
//! builtin registry as markdown (committed as SOMA_BUILTINS.md).

use crate::interpreter::builtins::registry;

pub fn cmd_docs(topic: &str) {
    match topic {
        "builtins" => print_builtins_markdown(),
        other => {
            eprintln!("error: unknown docs topic '{}'. Valid topics: [builtins]", other);
            std::process::exit(1);
        }
    }
}

/// Escape `|` so signatures survive inside a markdown table cell.
fn md_cell(s: &str) -> String {
    s.replace('|', "\\|")
}

fn print_builtins_markdown() {
    let total = registry::BUILTINS.len();
    let nondet: Vec<&str> = registry::BUILTINS.iter()
        .filter(|b| !b.deterministic)
        .map(|b| b.name)
        .collect();

    println!("# Soma Builtins");
    println!();
    println!("> GENERATED by `soma docs builtins` — do not edit by hand.");
    println!("> The source of truth is `compiler/src/interpreter/builtins/registry.rs`.");
    println!();
    println!("{} builtins. ✗ marks the nondeterministic set ({}) — calls to these", total, nondet.join(", "));
    println!("are tracked by `soma replay` as potential sources of replay divergence.");
    println!("`deterministic` is membership in that replay set, not a purity claim:");
    println!("think/http_*/read_*/next_id have effects but are replayed via the log itself.");

    for cat in registry::categories() {
        println!();
        println!("## {}", cat);
        println!();
        println!("| Builtin | Signature | Description |");
        println!("|---|---|---|");
        for b in registry::BUILTINS.iter().filter(|b| b.category == cat) {
            let marker = if b.deterministic { "" } else { " ✗" };
            println!("| `{}`{} | `{}` | {} |",
                b.name, marker, md_cell(b.signature), md_cell(b.brief));
        }
    }
}
