//! `soma docs` — render generated reference documentation.
//! The compiler is the single source of truth: this command renders the
//! builtin registry as markdown (committed as SOMA_BUILTINS.md).

use crate::interpreter::builtins::registry;

/// Hand-written references, embedded at build time: an agent without
/// network access still has the language, and the text cannot be newer or
/// older than the binary that prints it.
const AGENT_SUMMARY: &str = include_str!("../../../site/llms.txt");
const REFERENCE: &str = include_str!("../../../SOMA_REFERENCE.md");
const GOTCHAS: &str = include_str!("../../../AGENT_GOTCHAS.md");
const AGENTS_MD: &str = include_str!("../../../site/agent.md");

const TOPICS: &[(&str, &str)] = &[
    ("agent", "working summary of the language for a model's context (start here)"),
    ("reference", "the full language reference"),
    ("gotchas", "mistakes models make, each with the real diagnostic and the fix"),
    ("builtins", "every builtin with its exact signature, generated from the compiler"),
    ("agents-md", "drop-in AGENTS.md / CLAUDE.md block for a project that uses Soma"),
    ("all", "agent + reference + gotchas + builtins, one stream"),
];

pub fn cmd_docs(topic: &str) {
    match topic {
        "builtins" => print_builtins_markdown(),
        "agent" | "llms" => print!("{}", AGENT_SUMMARY),
        "reference" => print!("{}", REFERENCE),
        "gotchas" => print!("{}", GOTCHAS),
        "agents-md" => print!("{}", AGENTS_MD),
        "all" => {
            print!("{}\n\n---\n\n{}\n\n---\n\n{}\n\n---\n\n", AGENT_SUMMARY, REFERENCE, GOTCHAS);
            print_builtins_markdown();
        }
        "" | "topics" => {
            println!("soma docs <topic>\n");
            for (name, what) in TOPICS {
                println!("  {:<10} {}", name, what);
            }
            println!("\nOnline: https://soma-lang.dev/llms-full.txt");
        }
        other => {
            let names: Vec<&str> = TOPICS.iter().map(|(n, _)| *n).collect();
            eprintln!("error: unknown docs topic '{}'. Valid topics: [{}]", other, names.join(", "));
            std::process::exit(1);
        }
    }
}

/// Escape `|` so signatures survive inside a markdown table cell.
fn md_cell(s: &str) -> String {
    s.replace('|', "\\|")
}

fn print_builtins_markdown() {
    let total = registry::BUILTINS.len();
    let nondet: Vec<&str> = registry::BUILTINS.iter()
        .filter(|b| !b.deterministic)
        .map(|b| b.name)
        .collect();

    println!("# Soma Builtins");
    println!();
    println!("> GENERATED by `soma docs builtins` — do not edit by hand.");
    println!("> The source of truth is `compiler/src/interpreter/builtins/registry.rs`.");
    println!();
    println!("{} builtins. ✗ marks the nondeterministic set ({}) — calls to these", total, nondet.join(", "));
    println!("are tracked by `soma replay` as potential sources of replay divergence.");
    println!("`deterministic` is membership in that replay set, not a purity claim:");
    println!("think/http_*/read_*/next_id have effects but are replayed via the log itself.");

    for cat in registry::categories() {
        println!();
        println!("## {}", cat);
        println!();
        println!("| Builtin | Signature | Description |");
        println!("|---|---|---|");
        for b in registry::BUILTINS.iter().filter(|b| b.category == cat) {
            let marker = if b.deterministic { "" } else { " ✗" };
            println!("| `{}`{} | `{}` | {} |",
                b.name, marker, md_cell(b.signature), md_cell(b.brief));
        }
    }
}
