// Generated by Soma compiler — [native] handlers
// Do not edit — regenerate from .cell source

use rug::Integer;
use rug::Assign;


// Shared arg/result buffers for Rug-mode handlers.
// Int args go in _SOMA_ARGS; String args go in _SOMA_STRING_ARGS.
// Each buffer is a flat positional array; the handler param-reader knows
// which positional index in each buffer corresponds to which parameter.
static mut _SOMA_ARGS: Vec<Integer> = Vec::new();
static mut _SOMA_STRING_ARGS: Vec<String> = Vec::new();
static mut _SOMA_RESULT: Option<String> = None;

#[no_mangle]
pub extern "C" fn _soma_clear_args() {
    unsafe {
        _SOMA_ARGS.clear();
        _SOMA_STRING_ARGS.clear();
    }
}

#[no_mangle]
pub extern "C" fn _soma_push_i64(v: i64) {
    unsafe { _SOMA_ARGS.push(Integer::from(v)); }
}

#[no_mangle]
pub extern "C" fn _soma_push_bigint(ptr: *const u8, len: i64) {
    unsafe {
        let bytes = std::slice::from_raw_parts(ptr, len as usize);
        let s = std::str::from_utf8_unchecked(bytes);
        let val = Integer::parse(s).unwrap();
        _SOMA_ARGS.push(Integer::from(val));
    }
}

#[no_mangle]
pub extern "C" fn _soma_push_string(ptr: *const u8, len: i64) {
    unsafe {
        let bytes = std::slice::from_raw_parts(ptr, len as usize);
        _SOMA_STRING_ARGS.push(std::str::from_utf8_unchecked(bytes).to_string());
    }
}

#[no_mangle]
pub extern "C" fn _soma_result_ptr() -> *const u8 {
    unsafe { _SOMA_RESULT.as_ref().map(|s| s.as_ptr()).unwrap_or(std::ptr::null()) }
}

#[no_mangle]
pub extern "C" fn _soma_result_len() -> i64 {
    unsafe { _SOMA_RESULT.as_ref().map(|s| s.len() as i64).unwrap_or(0) }
}
fn inner_handler_catalan_str(mut n: Integer) -> String {
    let mut c: Integer = Integer::from(1i64);
    let mut i: i64 = 0i64;
    while i < n {
        c *= &Integer::from((4i64 * i) + 2i64);
        c /= &Integer::from(i + 2i64);
        i = (i + 1i64);
    }
    return c.to_string();
}

#[no_mangle]
pub extern "C" fn handler_catalan_str() -> i64 {
    let _ret_val: String = inner_handler_catalan_str(unsafe { _SOMA_ARGS[0].clone() });
    unsafe { _SOMA_RESULT = Some(_ret_val); }
    i64::MIN + 1
}

fn inner_handler_catalan_digits(mut n: Integer) -> Integer {
    let mut c: Integer = Integer::from(1i64);
    let mut i: i64 = 0i64;
    while i < n {
        c *= &Integer::from((4i64 * i) + 2i64);
        c /= &Integer::from(i + 2i64);
        i = (i + 1i64);
    }
    let mut d: i64 = 0i64;
    if c == 0i64 {
        return Integer::from(1i64);
    }
    while c > 0i64 {
        c /= 10u32;
        d = (d + 1i64);
    }
    return Integer::from(d);
}

#[no_mangle]
pub extern "C" fn handler_catalan_digits() -> i64 {
    let _ret_val: Integer = inner_handler_catalan_digits(unsafe { _SOMA_ARGS[0].clone() });
    if let Some(v) = _ret_val.to_i64() {
        v
    } else {
        unsafe { _SOMA_RESULT = Some(_ret_val.to_string()); }
        i64::MIN
    }
}

