// Generated by Soma compiler — [native] handlers
// Do not edit — regenerate from .cell source

static mut _SOMA_RNG_STATE: u64 = 0x12345678_9abcdef0;

#[inline(always)]
unsafe fn _soma_random() -> f64 {
    _SOMA_RNG_STATE ^= _SOMA_RNG_STATE >> 12;
    _SOMA_RNG_STATE ^= _SOMA_RNG_STATE << 25;
    _SOMA_RNG_STATE ^= _SOMA_RNG_STATE >> 27;
    let r = _SOMA_RNG_STATE.wrapping_mul(0x2545F4914F6CDD1D);
    (r >> 11) as f64 / ((1u64 << 53) as f64)
}

#[no_mangle]
pub extern "C" fn handler_vdc(n: i64) -> f64 {
    let mut result: f64 = 0f64;
    let mut base: f64 = 0.5f64;
    let mut num: f64 = n as f64;
    while (num > 0.0f64) {
        if ((num % 2.0f64) == 1.0f64) {
            result = (result + base);
        }
        num = (num / 2.0f64);
        base = (base / 2f64);
    }
    return result;
}

#[no_mangle]
pub extern "C" fn handler_inv_norm(u: f64) -> f64 {
    if (u <= 0.0001f64) {
        return -3.7f64;
    }
    if (u >= 0.9999f64) {
        return 3.7f64;
    }
    let mut t: f64 = (u - 0.5f64);
    if (t > -0.42f64) {
        if (t < 0.42f64) {
            let mut r: f64 = (t * t);
            let mut num: f64 = (t * ((((((-25.44106049637f64 * r) + 41.39119773534f64) * r) + -18.61500062529f64) * r) + 2.50662823884f64));
            let mut den: f64 = ((((((((3.13082909833f64 * r) + -21.06224101826f64) * r) + 23.08336743743f64) * r) + -8.4735109309f64) * r) + 1f64);
            return (num / den);
        }
    }
    let mut r: f64 = u;
    if (t > 0f64) {
        r = (1f64 - u);
    }
    let mut s: f64 = ((-1f64 * (r).ln())).ln();
    let mut z: f64 = (0.3374754822726147f64 + (s * (0.9761690190917186f64 + (s * (0.1607979714918209f64 + (s * (0.0276438810333863f64 + (s * 0.0038405729373609f64))))))));
    if (t < 0f64) {
        return (-1f64 * z);
    }
    return z;
}

#[no_mangle]
pub extern "C" fn handler_price_autocall_native(n_paths: i64, spot: f64, autocall_barrier: f64, coupon_barrier: f64, put_barrier: f64, coupon_rate: f64, r: f64, sigma: f64, n_obs: i64, dt: f64, use_sobol: i64) -> f64 {
    let mut total_pv: f64 = 0f64;
    let mut path: i64 = 0i64;
    while (path < n_paths) {
        let mut s_price: f64 = spot;
        let mut redeemed: i64 = 0i64;
        let mut pv: f64 = 0f64;
        let mut obs: i64 = 0i64;
        while (obs < n_obs) {
            let mut z: f64 = 0f64;
            if (use_sobol == 1i64) {
                let mut u: f64 = handler_vdc((((path * n_obs) + obs) + 1i64));
                z = handler_inv_norm(u);
            } else {
                let mut u: f64 = unsafe { _soma_random() };
                if (u < 0.0001f64) {
                    u = 0.0001f64;
                }
                if (u > 0.9999f64) {
                    u = 0.9999f64;
                }
                z = handler_inv_norm(u);
            }
            let mut drift: f64 = ((r - ((0.5f64 * sigma) * sigma)) * dt);
            let mut diffusion: f64 = ((sigma * (dt).sqrt()) * z);
            s_price = (s_price * ((drift + diffusion)).exp());
            let mut t: f64 = (((obs + 1i64) as f64) * dt);
            let mut df: f64 = (((-1f64 * r) * t)).exp();
            if (s_price >= autocall_barrier) {
                if (redeemed == 0i64) {
                    pv = (df * (100f64 + ((coupon_rate * ((obs + 1i64) as f64)) * dt)));
                    redeemed = 1i64;
                }
            }
            obs = (obs + 1i64);
        }
        if (redeemed == 0i64) {
            let mut mat_T: f64 = (n_obs as f64 * dt);
            let mut df: f64 = (((-1f64 * r) * mat_T)).exp();
            if (s_price >= coupon_barrier) {
                pv = (df * (100f64 + (coupon_rate * mat_T)));
            } else {
                if (s_price < put_barrier) {
                    pv = (df * ((s_price / spot) * 100f64));
                } else {
                    pv = (df * 100f64);
                }
            }
        }
        total_pv = (total_pv + pv);
        path = (path + 1i64);
    }
    return (total_pv / n_paths as f64);
}

