// Generated by Soma compiler — [native] handlers
// Do not edit — regenerate from .cell source

static mut _SOMA_RNG_STATE: u64 = 0x12345678_9abcdef0;

#[inline(always)]
unsafe fn _soma_random() -> f64 {
    _SOMA_RNG_STATE ^= _SOMA_RNG_STATE >> 12;
    _SOMA_RNG_STATE ^= _SOMA_RNG_STATE << 25;
    _SOMA_RNG_STATE ^= _SOMA_RNG_STATE >> 27;
    let r = _SOMA_RNG_STATE.wrapping_mul(0x2545F4914F6CDD1D);
    (r >> 11) as f64 / ((1u64 << 53) as f64)
}

#[no_mangle]
pub extern "C" fn handler_compute_path(i: i64) -> f64 {
    let mut x: f64 = unsafe { _soma_random() };
    let mut y: f64 = unsafe { _soma_random() };
    if (((x * x) + (y * y)) <= 1f64) {
        return 1f64;
    }
    return 0f64;
}

#[no_mangle]
pub extern "C" fn handler_simulate_pipe(n: i64) -> f64 {
    return /* unsupported pipe */ {
let _src: Vec<f64> = (0i64..n).map(|i| i as f64).collect();
let _n = _src.len();
let _ncpu = std::thread::available_parallelism().map(|n| n.get()).unwrap_or(1);
if _n < _ncpu * 1000 {
_src.iter().map(|i| { handler_compute_path(i) }).collect::<Vec<f64>>()
} else {
let _chunk = (_n + _ncpu - 1) / _ncpu;
std::thread::scope(|_s| {
let _handles: Vec<_> = (0.._ncpu).map(|_t| {
let _slice = &_src[(_t * _chunk).min(_n)..((_t + 1) * _chunk).min(_n)];
_s.spawn(move || _slice.iter().map(|i| { handler_compute_path(i) }).collect::<Vec<f64>>())
}).collect();
_handles.into_iter().flat_map(|h| h.join().unwrap()).collect::<Vec<f64>>()
})
}
};
}

#[no_mangle]
pub extern "C" fn handler_simulate_loop(n: i64) -> f64 {
    let mut total: f64 = 0f64;
    let mut i: i64 = 0i64;
    while (i < n) {
        let mut x: f64 = unsafe { _soma_random() };
        let mut y: f64 = unsafe { _soma_random() };
        if (((x * x) + (y * y)) <= 1f64) {
            total = (total + 1f64);
        }
        i = (i + 1i64);
    }
    return ((4f64 * total) / n as f64);
}

