// Generated by Soma compiler — [native] handlers
// Do not edit — regenerate from .cell source
use num_bigint::BigInt;
use num_traits::ToPrimitive;

static mut _RESULT_HANDLER_SUM_CUBES: Option<String> = None;

#[no_mangle]
pub extern "C" fn handler_sum_cubes(n: i64) -> i64 {
    // Suppress panic messages for expected overflow
    std::panic::set_hook(Box::new(|_| {}));
    let _fast = std::panic::catch_unwind(|| -> i64 {
        let mut s: i64 = (0i64);
        let mut i: i64 = (0i64);
        while ((i) < (n)) {
            s = ((s) + (((i) * (i)) * (i)));
            i = ((i) + (1i64));
        }
        { let _ret_val = (s);
                match Some(_ret_val) {
            Some(v) => return v,
            None => {
                unsafe { _RESULT_HANDLER_SUM_CUBES = Some(_ret_val.to_string()); }
                return i64::MIN;
            }
        }}
    });
    let _ = std::panic::take_hook(); // restore default hook
    if let Ok(v) = _fast { return v; }

    // Overflow — BigInt fallback
    let n = BigInt::from(n);
    let mut s: BigInt = BigInt::from(0i64);
    let mut i: BigInt = BigInt::from(0i64);
    while ((&i) < (&n)) {
        s = ((&s) + (((&i) * (&i)) * (&i)));
        i = ((&i) + BigInt::from(1i64));
    }
    { let _ret_val = (&s);
    use num_traits::ToPrimitive;
    match _ret_val.to_i64() {
        Some(v) => return v,
        None => {
            unsafe { _RESULT_HANDLER_SUM_CUBES = Some(_ret_val.to_string()); }
            return i64::MIN;
        }
    }}
}

#[no_mangle]
pub extern "C" fn handler_sum_cubes_bigint_result() -> *const u8 {
    unsafe { _RESULT_HANDLER_SUM_CUBES.as_ref().map(|s| s.as_ptr()).unwrap_or(std::ptr::null()) }
}

#[no_mangle]
pub extern "C" fn handler_sum_cubes_bigint_len() -> i64 {
    unsafe { _RESULT_HANDLER_SUM_CUBES.as_ref().map(|s| s.len() as i64).unwrap_or(0) }
}

