// Generated by Soma compiler — [native] handlers
// Do not edit — regenerate from .cell source

static mut _SOMA_RNG_STATE: u64 = 0x12345678_9abcdef0;

#[inline(always)]
unsafe fn _soma_random() -> f64 {
    _SOMA_RNG_STATE ^= _SOMA_RNG_STATE >> 12;
    _SOMA_RNG_STATE ^= _SOMA_RNG_STATE << 25;
    _SOMA_RNG_STATE ^= _SOMA_RNG_STATE >> 27;
    let r = _SOMA_RNG_STATE.wrapping_mul(0x2545F4914F6CDD1D);
    (r >> 11) as f64 / ((1u64 << 53) as f64)
}

#[no_mangle]
pub extern "C" fn handler_simulate(n: i64) -> f64 {
    let mut total: f64 = 0f64;
    let mut i: i64 = 0i64;
    while (i < n) {
        let mut x: f64 = unsafe { _soma_random() };
        let mut y: f64 = unsafe { _soma_random() };
        if (((x * x) + (y * y)) <= 1f64) {
            total = (total + 1f64);
        }
        i = (i + 1i64);
    }
    return ((4f64 * total) / n as f64);
}

#[no_mangle]
pub extern "C" fn handler_simulate_par(n: i64) -> f64 {
	let _n_threads = 8usize;
	let _total = n as usize;
	if _total < _n_threads * 1000 {
		return handler_simulate(n);
	}
	let _chunk = (_total + _n_threads - 1) / _n_threads;
	let _result: f64 = std::thread::scope(|_s| {
		let _handles: Vec<_> = (0.._n_threads).map(|_t| {
			let _start = _t * _chunk;
			let _end = std::cmp::min((_t + 1) * _chunk, _total);
			let _chunk_n = (_end - _start) as i64;
			_s.spawn(move || {
				handler_simulate(_chunk_n) * _chunk_n as f64
			})
		}).collect();
		_handles.into_iter().map(|h| h.join().unwrap()).sum::<f64>()
	});
	(_result / n as f64) as f64
}

