// Generated by Soma compiler — [native] handlers
// Do not edit — regenerate from .cell source

static mut _SOMA_RNG_STATE: u64 = 0x12345678_9abcdef0;

#[inline(always)]
unsafe fn _soma_random() -> f64 {
    _SOMA_RNG_STATE ^= _SOMA_RNG_STATE >> 12;
    _SOMA_RNG_STATE ^= _SOMA_RNG_STATE << 25;
    _SOMA_RNG_STATE ^= _SOMA_RNG_STATE >> 27;
    let r = _SOMA_RNG_STATE.wrapping_mul(0x2545F4914F6CDD1D);
    (r >> 11) as f64 / ((1u64 << 53) as f64)
}

#[no_mangle]
pub extern "C" fn handler_compute_hit(i: i64) -> f64 {
    let mut x: f64 = unsafe { _soma_random() };
    let mut y: f64 = unsafe { _soma_random() };
    if (((x * x) + (y * y)) <= 1f64) {
        return 1f64;
    }
    return 0f64;
}

#[no_mangle]
pub extern "C" fn handler_simulate_pipe(n: i64) -> f64 {
    return ((((0i64..n)).map(|i| -> f64 { handler_compute_hit(i) })).fold(0f64, |_acc, _val| { let _val = _val as f64; (_acc + _val) }) / n as f64 * 4f64);
}

#[no_mangle]
pub extern "C" fn handler_simulate_loop(n: i64) -> f64 {
    let mut total: f64 = 0f64;
    let mut i: i64 = 0i64;
    while (i < n) {
        let mut x: f64 = unsafe { _soma_random() };
        let mut y: f64 = unsafe { _soma_random() };
        if (((x * x) + (y * y)) <= 1f64) {
            total = (total + 1f64);
        }
        i = (i + 1i64);
    }
    return ((4f64 * total) / n as f64);
}

