// Generated by Soma compiler — [native] handlers
// Do not edit — regenerate from .cell source

#[inline(always)]
fn _inner_handler_sum_cubes(n: i64) -> i128 {
    let n = n as i128;
    let mut s: i128 = 0i128;
    let mut i: i128 = 0i128;
    while (i < n) {
        s = (s + ((i * i) * i));
        i = (i + 1i128);
    }
    return s;
}

static mut _OVERFLOW_HANDLER_SUM_CUBES: i64 = 0;
static mut _OVERFLOW_HI_HANDLER_SUM_CUBES: i64 = 0;

#[no_mangle]
pub extern "C" fn handler_sum_cubes(n: i64) -> i64 {
    let _r = _inner_handler_sum_cubes(n);
    unsafe { _OVERFLOW_HANDLER_SUM_CUBES = if _r > i64::MAX as i128 || _r < i64::MIN as i128 { 1 } else { 0 }; }
    unsafe { _OVERFLOW_HI_HANDLER_SUM_CUBES = (_r >> 64) as i64; }
    _r as i64
}

#[no_mangle]
pub extern "C" fn handler_sum_cubes_overflow() -> i64 {
    unsafe { _OVERFLOW_HANDLER_SUM_CUBES }
}

#[no_mangle]
pub extern "C" fn handler_sum_cubes_hi() -> i64 {
    unsafe { _OVERFLOW_HI_HANDLER_SUM_CUBES }
}

