// Generated by Soma compiler — [native] handlers
// Do not edit — regenerate from .cell source
use num_bigint::BigInt;
use num_traits::ToPrimitive;

static mut _RESULT_HANDLER_F: Option<String> = None;


/// A value that starts as i64 and promotes to BigInt on overflow
enum V { S(i64), B(BigInt) }
impl V {
    fn add(&mut self, other: i64) {
        *self = match self {
            V::S(a) => match a.checked_add(other) {
                Some(r) => V::S(r),
                None => V::B(BigInt::from(*a) + other),
            },
            V::B(a) => { *a += other; return; }
        };
    }
    fn sub(&mut self, other: i64) {
        *self = match self {
            V::S(a) => match a.checked_sub(other) {
                Some(r) => V::S(r),
                None => V::B(BigInt::from(*a) - other),
            },
            V::B(a) => { *a -= other; return; }
        };
    }
    fn mul_v(&mut self, other: &V) {
        *self = match (&*self, other) {
            (V::S(a), V::S(b)) => match a.checked_mul(*b) {
                Some(r) => V::S(r),
                None => V::B(BigInt::from(*a) * *b),
            },
            (V::S(a), V::B(b)) => V::B(BigInt::from(*a) * b),
            (V::B(a), V::S(b)) => V::B(a.clone() * *b),
            (V::B(a), V::B(b)) => V::B(a.clone() * b),
        };
    }
    fn add_v(&mut self, other: &V) {
        *self = match (&*self, other) {
            (V::S(a), V::S(b)) => match a.checked_add(*b) {
                Some(r) => V::S(r),
                None => V::B(BigInt::from(*a) + *b),
            },
            (V::S(a), V::B(b)) => V::B(BigInt::from(*a) + b),
            (V::B(a), V::S(b)) => V::B(a.clone() + *b),
            (V::B(a), V::B(b)) => V::B(a.clone() + b),
        };
    }
    fn sub_v(&mut self, other: &V) {
        *self = match (&*self, other) {
            (V::S(a), V::S(b)) => match a.checked_sub(*b) {
                Some(r) => V::S(r),
                None => V::B(BigInt::from(*a) - *b),
            },
            (V::S(a), V::B(b)) => V::B(BigInt::from(*a) - b),
            (V::B(a), V::S(b)) => V::B(a.clone() - *b),
            (V::B(a), V::B(b)) => V::B(a.clone() - b),
        };
    }
    fn to_i64(&self) -> Option<i64> {
        match self { V::S(n) => Some(*n), V::B(n) => n.to_i64() }
    }
    fn to_bigint(&self) -> BigInt {
        match self { V::S(n) => BigInt::from(*n), V::B(n) => n.clone() }
    }
    fn le_v(&self, other: &V) -> bool {
        match (self, other) {
            (V::S(a), V::S(b)) => *a <= *b,
            (V::S(a), V::B(b)) => BigInt::from(*a) <= *b,
            (V::B(a), V::S(b)) => *a <= BigInt::from(*b),
            (V::B(a), V::B(b)) => *a <= *b,
        }
    }
    fn lt_v(&self, other: &V) -> bool {
        match (self, other) {
            (V::S(a), V::S(b)) => *a < *b,
            (V::S(a), V::B(b)) => BigInt::from(*a) < *b,
            (V::B(a), V::S(b)) => *a < BigInt::from(*b),
            (V::B(a), V::B(b)) => *a < *b,
        }
    }
    fn clone_v(&self) -> V {
        match self { V::S(n) => V::S(*n), V::B(n) => V::B(n.clone()) }
    }
}
impl std::fmt::Display for V {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self { V::S(n) => write!(f, "{}"  , n), V::B(n) => write!(f, "{}"  , n) }
    }
}
#[no_mangle]
pub extern "C" fn handler_f(n: i64) -> i64 {
    let n = V::S(n);
    let mut r: V = V::S(1i64);
    let mut i: V = V::S(1i64);
    while i.le_v(&n) {
        r.mul_v(&i);
        i.add(1i64);
    }
    { let _ret_val = r.clone_v();
    use num_traits::ToPrimitive;
    match _ret_val.to_i64() {
        Some(v) => return v,
        None => {
            unsafe { _RESULT_HANDLER_F = Some(_ret_val.to_string()); }
            return i64::MIN;
        }
    }}
}

#[no_mangle]
pub extern "C" fn handler_f_bigint_result() -> *const u8 {
    unsafe { _RESULT_HANDLER_F.as_ref().map(|s| s.as_ptr()).unwrap_or(std::ptr::null()) }
}

#[no_mangle]
pub extern "C" fn handler_f_bigint_len() -> i64 {
    unsafe { _RESULT_HANDLER_F.as_ref().map(|s| s.len() as i64).unwrap_or(0) }
}

