// Generated by Soma compiler — [native] handlers
// Do not edit — regenerate from .cell source
use num_bigint::BigInt;
use num_traits::ToPrimitive;

static mut _RESULT_HANDLER_FACTORIAL: Option<String> = None;

#[no_mangle]
pub extern "C" fn handler_factorial(n: i64) -> i64 {
    let n = BigInt::from(n);
    let mut result: BigInt = BigInt::from(1i64);
    let mut i: BigInt = BigInt::from(1i64);
    while (i.clone() <= n.clone()) {
        result = (result.clone() * i.clone());
        i = (i.clone() + BigInt::from(1i64));
    }
    { let _ret_val = result.clone();
    use num_traits::ToPrimitive;
    match _ret_val.to_i64() {
        Some(v) => return v,
        None => {
            unsafe { _RESULT_HANDLER_FACTORIAL = Some(_ret_val.to_string()); }
            return i64::MIN;
        }
    }}
}

#[no_mangle]
pub extern "C" fn handler_factorial_bigint_result() -> *const u8 {
    unsafe { _RESULT_HANDLER_FACTORIAL.as_ref().map(|s| s.as_ptr()).unwrap_or(std::ptr::null()) }
}

#[no_mangle]
pub extern "C" fn handler_factorial_bigint_len() -> i64 {
    unsafe { _RESULT_HANDLER_FACTORIAL.as_ref().map(|s| s.len() as i64).unwrap_or(0) }
}

